<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\ExerciseCategory;
use Illuminate\Database\Seeder;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Storage;

class BarbellSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ExerciseCategory::pluck('id', 'slug');

        $execises = [
            ['name' => 'Barbell Back Squat', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Adductors', 'Erector Spinae', 'Core'], 'description' => 'Position the bar across the upper back, squat down until thighs are at least parallel, then drive back up to standing without locking out the knees. The foundational lower-body strength exercise.'],
            ['name' => 'Barbell Front Squat', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Core', 'Upper Back'], 'description' => 'Rest the barbell across the front deltoids with elbows high, squat down while keeping an upright torso, then stand up. Emphasises the quads and core.'],
            ['name' => 'Barbell Overhead Squat', 'equipment' => 'Barbell', 'category_slug' => 'mobility', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Shoulders', 'Core', 'Upper Back'], 'description' => 'Press the barbell overhead with a wide snatch grip, lock arms, and squat deeply while maintaining a stable overhead position. Demands extreme shoulder mobility and core stability.'],
            ['name' => 'Barbell Zercher Squat', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core', 'Biceps'], 'description' => 'Hold the barbell in the crooks of the elbows, squat down while keeping the bar against the body, then drive up. Challenges the upper back and biceps.'],
            ['name' => 'Barbell Box Squat', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Adductors', 'Erector Spinae'], 'description' => 'Place a box behind you, squat until you sit briefly on the box, then explosively stand up. Teaches proper depth and develops starting strength.'],
            ['name' => 'Barbell Pause Squat', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Erector Spinae', 'Core'], 'description' => 'Descend into a squat and hold the bottom position for 1-3 seconds without bouncing, then drive upward. Eliminates stretch reflex and builds explosive power.'],
            ['name' => 'Barbell Tempo Squat (3-1-3)', 'equipment' => 'Barbell', 'category_slug' => 'hypertrophy', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Take 3 seconds to lower, pause 1 second at the bottom, then take 3 seconds to rise. Maximises time under tension.'],
            ['name' => 'Barbell Pin Squat', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Adductors'], 'description' => 'Set the safety pins at your sticking point, lower the barbell onto them, release tension, then explosively drive back up. Builds force from a dead stop.'],
            ['name' => 'Barbell Anderson Squat (Bottom-Up)', 'equipment' => 'Barbell', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Erector Spinae'], 'description' => 'Start with the barbell resting on safety pins at the bottom squat depth, then drive up without any eccentric phase to build explosive starting strength.'],
            ['name' => 'Barbell Bulgarian Split Squat', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Place a bench behind you, rest the rear foot on it with the barbell on your back, squat down until the front thigh is parallel. Excellent unilateral leg builder.'],
            ['name' => 'Barbell Reverse Lunge', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'With the barbell on your back, step backward into a deep lunge, drop the rear knee, then push back to start. Unilateral strength and stability.'],
            ['name' => 'Barbell Walking Lunge', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'With the barbell on your back, perform alternating forward lunges while walking continuously. Challenges balance and endurance.'],
            ['name' => 'Barbell Conventional Deadlift', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Erector Spinae', 'Quadriceps', 'Traps', 'Grip'], 'description' => 'Stand with feet hip-width, grip the barbell just outside the legs, keep the back flat, and pull by extending hips and knees until standing. The king of posterior chain execises.'],
            ['name' => 'Barbell Sumo Deadlift', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Adductors', 'Quadriceps', 'Erector Spinae', 'Traps'], 'description' => 'Take a wide stance with hands inside the knees, pull the barbell by driving the hips forward. Emphasises the inner thighs and hips.'],
            ['name' => 'Barbell Romanian Deadlift', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Erector Spinae'], 'description' => 'With a slight knee bend, hinge at the hips and lower the barbell along the thighs, feeling a deep hamstring stretch, then return by extending the hips.'],
            ['name' => 'Barbell Stiff-Leg Deadlift', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Erector Spinae'], 'description' => 'Keep the legs nearly straight, push the hips back to lower the barbell toward the floor, stretching the hamstrings, then return to standing.'],
            ['name' => 'Barbell Deficit Deadlift', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Erector Spinae', 'Quadriceps'], 'description' => 'Stand on a small platform to increase the range of motion, then perform a conventional deadlift. Enhances strength off the floor.'],
            ['name' => 'Barbell Snatch-Grip Deadlift', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Erector Spinae', 'Glutes', 'Hamstrings', 'Upper Back', 'Traps'], 'description' => 'Use a wide snatch grip, which increases the range of motion and places more emphasis on the upper back and spinal erectors.'],
            ['name' => 'Barbell Rack Pull', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Erector Spinae', 'Traps', 'Grip'], 'description' => 'Set the safety pins just below the knees, then pull the barbell from this elevated position. Overloads the lockout portion of the deadlift.'],
            ['name' => 'Barbell Pause Deadlift', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Erector Spinae', 'Core'], 'description' => 'Pull the barbell just off the floor, hold for 1-2 seconds, then complete the lift. Eliminates momentum and builds starting strength.'],
            ['name' => 'Barbell Flat Bench Press', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids', 'Triceps'], 'description' => 'Lie on a flat bench, grip the barbell slightly wider than shoulder-width, lower to mid-chest, and press up to full lockout. The cornerstone of upper body pressing.'],
            ['name' => 'Barbell Incline Bench Press', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Upper Pectoralis', 'Anterior Deltoids', 'Triceps'], 'description' => 'Set the bench to 30-45, press the barbell from the upper chest. Targets the clavicular head of the pecs.'],
            ['name' => 'Barbell Decline Bench Press', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Lower Pectoralis', 'Anterior Deltoids', 'Triceps'], 'description' => 'On a decline bench, lower the barbell to the lower sternum, press up to emphasise the lower chest.'],
            ['name' => 'Barbell Close-Grip Bench Press', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Triceps', 'Inner Pectoralis', 'Anterior Deltoids'], 'description' => 'Use a shoulder-width grip, lower the barbell to the lower chest with elbows tucked. Shifts the load to the triceps.'],
            ['name' => 'Barbell Wide-Grip Bench Press', 'equipment' => 'Barbell', 'category_slug' => 'hypertrophy', 'target_muscles' => ['Pectoralis Major (Outer)', 'Anterior Deltoids', 'Triceps'], 'description' => 'Grip significantly wider than shoulder-width to increase chest stretch and outer pec activation.'],
            ['name' => 'Barbell Reverse-Grip Bench Press', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Upper Pectoralis', 'Triceps', 'Anterior Deltoids'], 'description' => 'Grip the barbell with palms facing up, lower to the lower chest. This alters the elbow path, hitting the upper chest and triceps.'],
            ['name' => 'Barbell Floor Press', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Triceps', 'Pectoralis Major', 'Anterior Deltoids'], 'description' => 'Lie on the floor inside a power rack, barbell on the safety pins. Press up from a dead stop. Emphasises lockout strength.'],
            ['name' => 'Barbell Board Press', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Triceps', 'Pectoralis Major', 'Anterior Deltoids'], 'description' => 'Place wooden boards on the chest to shorten the range of motion, pressing from a higher point. Isolates lockout and tricep power.'],
            ['name' => 'Barbell Pause Bench Press', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'], 'description' => 'Lower the barbell to the chest, pause for 1-3 seconds without sinking, then press explosively. Builds off-the-chest strength.'],
            ['name' => 'Barbell Tempo Bench Press (3-1-3)', 'equipment' => 'Barbell', 'category_slug' => 'hypertrophy', 'target_muscles' => ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'], 'description' => 'Take 3 seconds to lower, pause 1 second at the chest, then take 3 seconds to press. Maximises time under tension.'],
            ['name' => 'Barbell Larsen Press', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'], 'description' => 'Lie on a flat bench with feet raised off the floor, reducing leg drive and forcing the pecs and triceps to do all the work.'],
            ['name' => 'Barbell Guillotine Press (Neck Press)', 'equipment' => 'Barbell', 'category_slug' => 'hypertrophy', 'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids'], 'description' => 'Lower the barbell to the neck area with elbows flared wide, then press up. Deeply stretches the chest and reduces tricep involvement.'],
            ['name' => 'Barbell Standing Overhead Press (Strict Press)', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Upper Traps', 'Core'], 'description' => 'Stand, grip the barbell at shoulder width, and press overhead without using leg drive. The ultimate test of shoulder strength.'],
            ['name' => 'Barbell Seated Overhead Press', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps'], 'description' => 'Sit on a bench with back support, press the barbell overhead from shoulder height. Isolates the deltoids and reduces lower body involvement.'],
            ['name' => 'Barbell Push Press', 'equipment' => 'Barbell', 'category_slug' => 'power', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Quadriceps', 'Core'], 'description' => 'Dip slightly at the knees, then explode upward and press the barbell overhead using leg drive. Allows more weight than a strict press.'],
            ['name' => 'Barbell Push Jerk', 'equipment' => 'Barbell', 'category_slug' => 'power', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Quadriceps', 'Glutes', 'Core'], 'description' => 'Dip, drive the barbell overhead, and re-dip under the bar to catch it with locked arms before standing. Olympic-style lift.'],
            ['name' => 'Barbell Split Jerk', 'equipment' => 'Barbell', 'category_slug' => 'power', 'target_muscles' => ['Deltoids', 'Triceps', 'Quadriceps', 'Glutes'], 'description' => 'Drive the barbell overhead and split the legs into a lunge position to catch the bar, then recover. The standard competition jerk.'],
            ['name' => 'Barbell Behind-the-Neck Press', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Upper Traps'], 'description' => 'Press the barbell from behind the neck to overhead. Requires good shoulder mobility and strongly targets the medial delts.'],
            ['name' => 'Barbell Bent-Over Row (Overhand)', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Traps', 'Rear Deltoids', 'Biceps', 'Erector Spinae'], 'description' => 'Hinge forward with a flat back, grip the barbell with hands wider than shoulder-width, and pull to the lower abdomen, squeezing shoulder blades.'],
            ['name' => 'Barbell Bent-Over Row (Underhand / Yates Row)', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Rhomboids', 'Middle Traps', 'Erector Spinae'], 'description' => 'Use an underhand grip and a more upright torso angle, pulling the barbell to the lower belly. Increases bicep involvement.'],
            ['name' => 'Barbell Pendlay Row', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Traps', 'Rear Deltoids', 'Biceps', 'Erector Spinae'], 'description' => 'Start each rep with the barbell on the floor, back parallel to the ground, and pull explosively to the sternum, then reset on the floor.'],
            ['name' => 'Barbell T-Bar Row (Landmine)', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Middle Traps', 'Biceps', 'Erector Spinae'], 'description' => 'Place one end of the barbell in a landmine or corner, load plates on the other end, straddle the bar, and row the weight to the chest using a V-grip handle or direct grip.'],
            ['name' => 'Barbell Seal Row', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Biceps', 'Rear Deltoids'], 'description' => 'Lie face down on a high bench, letting the barbell hang, and row it up to the bench. Eliminates spinal loading and isolates the back.'],
            ['name' => 'Barbell Upright Row', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Medial Deltoids', 'Upper Traps', 'Biceps', 'Forearms'], 'description' => 'Grip the barbell with a narrow overhand grip, pull it up along the body to chin height, leading with the elbows.'],
            ['name' => 'Barbell High Pull', 'equipment' => 'Barbell', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Shoulders', 'Traps', 'Core'], 'description' => 'From a hang or floor position, explosively extend the hips and knees while pulling the barbell upward to chest height with wide elbows.'],
            ['name' => 'Barbell Shrug', 'equipment' => 'Barbell', 'category_slug' => 'isolation', 'target_muscles' => ['Upper Trapezius', 'Levator Scapulae'], 'description' => 'Hold the barbell at arms length in front of the thighs, shrug the shoulders straight up toward the ears, squeeze, and lower.'],
            ['name' => 'Barbell Pullover (Straight Arm)', 'equipment' => 'Barbell', 'category_slug' => 'isolation', 'target_muscles' => ['Latissimus Dorsi', 'Pectoralis Major', 'Serratus Anterior', 'Triceps Long Head'], 'description' => 'Lie across a bench with upper back supported, hold a barbell with straight arms overhead, and pull it in an arc over the chest until its above the hips.'],
            ['name' => 'Barbell Biceps Curl', 'equipment' => 'Barbell', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps Brachii', 'Brachialis'], 'description' => 'Stand holding the barbell with an underhand grip, curl the bar up by flexing the elbows, squeeze at the top, then lower with control.'],
            ['name' => 'Barbell Reverse Curl', 'equipment' => 'Barbell', 'category_slug' => 'isolation', 'target_muscles' => ['Brachioradialis', 'Wrist Extensors', 'Biceps'], 'description' => 'Use a pronated (overhand) grip, curl the barbell upward, keeping elbows stationary. Emphasises the forearms and brachioradialis.'],
            ['name' => 'Barbell Drag Curl', 'equipment' => 'Barbell', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps Brachii', 'Brachialis'], 'description' => 'Slide the barbell up the front of the torso, elbows moving back, keeping constant tension on the biceps.'],
            ['name' => 'Barbell Preacher Curl', 'equipment' => 'Barbell', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps Brachii', 'Brachialis'], 'description' => 'Using a preacher bench, curl the barbell with the upper arms supported, ensuring strict form and peak contraction.'],
            ['name' => 'Barbell Lying Triceps Extension (Skull Crusher)', 'equipment' => 'Barbell', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps Brachii'], 'description' => 'Lie on a bench, press the barbell overhead, then lower it toward the forehead by bending the elbows, then extend back up.'],
            ['name' => 'Barbell Overhead Triceps Extension', 'equipment' => 'Barbell', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps Brachii (Long Head)'], 'description' => 'Sit or stand holding the barbell overhead, lower it behind the head by bending the elbows, then extend to lockout.'],
            ['name' => 'Barbell JM Press', 'equipment' => 'Barbell', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps', 'Pectorals'], 'description' => 'A hybrid between a close-grip bench press and a skull crusher. Lower the barbell to the chin or upper chest while keeping the elbows slightly flared, then drive back.'],
            ['name' => 'Barbell Hip Thrust', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Core'], 'description' => 'Sit on the floor with upper back against a bench, place the barbell across the hips, drive through the heels to extend hips to full lockout, squeezing the glutes.'],
            ['name' => 'Barbell Glute Bridge', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings'], 'description' => 'Lie on the floor, barbell across the hips, push through the feet to lift the hips until the body forms a straight line from shoulders to knees.'],
            ['name' => 'Barbell Good Morning', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Erector Spinae', 'Core'], 'description' => 'With the barbell on the upper back, hinge forward at the hips while keeping the back flat, then return to standing. Strengthens the entire posterior chain.'],
            ['name' => 'Barbell Seated Good Morning', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Erector Spinae', 'Glutes'], 'description' => 'Sit on a bench with the barbell on the back, hinge forward at the hips while maintaining a flat back. Isolates the spinal erectors.'],
            ['name' => 'Barbell Standing Calf Raise', 'equipment' => 'Barbell', 'category_slug' => 'isolation', 'target_muscles' => ['Gastrocnemius', 'Soleus'], 'description' => 'With the barbell on the back, place the balls of the feet on a block, raise the heels as high as possible, then lower for a stretch.'],
            ['name' => 'Barbell Seated Calf Raise', 'equipment' => 'Barbell', 'category_slug' => 'isolation', 'target_muscles' => ['Soleus', 'Gastrocnemius'], 'description' => 'Sit on a bench, place the barbell across the thighs just above the knees, and perform calf raises by extending the ankles.'],
            ['name' => 'Barbell Rollout (Ab Wheel Substitute)', 'equipment' => 'Barbell', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Transverse Abdominis', 'Obliques', 'Erector Spinae', 'Shoulders'], 'description' => 'Load the barbell with small plates, kneel on the floor, and roll the barbell forward extending the body, then pull back using the core.'],
            ['name' => 'Barbell Floor Wiper', 'equipment' => 'Barbell', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis', 'Shoulders'], 'description' => 'Lie on your back holding the barbell overhead with locked arms, legs straight up. Lower the legs side to side while keeping the barbell stable.'],
            ['name' => 'Barbell Landmine Russian Twist', 'equipment' => 'Barbell', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis'], 'description' => 'Stand holding the end of a landmine barbell, rotate the torso side to side while the bar moves in an arc, engaging the obliques.'],
            ['name' => 'Barbell Suitcase Carry (Partial)', 'equipment' => 'Barbell', 'category_slug' => 'stability', 'target_muscles' => ['Obliques', 'Core', 'Forearms', 'Traps', 'Gluteus Medius'], 'description' => 'Carry a barbell in one hand like a suitcase, keeping the torso upright and resisting lateral lean. Walk for distance.'],
            ['name' => 'Barbell Power Clean', 'equipment' => 'Barbell', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Traps', 'Deltoids', 'Core'], 'description' => 'From the floor, explosively pull the barbell and catch it on the shoulders in a front rack with a slight dip. A full-body power movement.'],
            ['name' => 'Barbell Squat Clean', 'equipment' => 'Barbell', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Shoulders', 'Core'], 'description' => 'Pull the barbell from the floor and catch it in a deep front squat position, then stand. Develops strength through a full range of motion.'],
            ['name' => 'Barbell Hang Clean', 'equipment' => 'Barbell', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Shoulders', 'Traps'], 'description' => 'Start with the barbell at hip level, dip, then explosively pull and catch it in a front rack. Emphasises the second pull.'],
            ['name' => 'Barbell Power Snatch', 'equipment' => 'Barbell', 'category_slug' => 'power', 'target_muscles' => ['Glutes', 'Hamstrings', 'Shoulders', 'Triceps', 'Upper Back', 'Core'], 'description' => 'In one explosive motion, pull the barbell from the floor and catch it overhead with a slight dip, arms locked. Develops speed and power.'],
            ['name' => 'Barbell Squat Snatch', 'equipment' => 'Barbell', 'category_slug' => 'power', 'target_muscles' => ['Glutes', 'Hamstrings', 'Quadriceps', 'Shoulders', 'Core'], 'description' => 'Pull the barbell from the floor and catch it in a deep overhead squat. Requires extreme mobility, balance, and strength.'],
            ['name' => 'Barbell Hang Snatch', 'equipment' => 'Barbell', 'category_slug' => 'power', 'target_muscles' => ['Shoulders', 'Glutes', 'Hamstrings', 'Upper Back', 'Core'], 'description' => 'Start with the barbell at the hips, dip, then pull and catch overhead. Focuses on the violent upward extension.'],
            ['name' => 'Barbell Push Jerk from Rack', 'equipment' => 'Barbell', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Deltoids', 'Triceps', 'Core'], 'description' => 'With the barbell on the shoulders, dip, drive, and press under the bar to catch it overhead with a slight re-bend of the knees, then stand.'],
            ['name' => 'Barbell Clean & Jerk (Full)', 'equipment' => 'Barbell', 'category_slug' => 'power', 'target_muscles' => ['Full Body', 'Legs', 'Back', 'Shoulders', 'Core'], 'description' => 'Combine a squat clean with a split jerk: pull the bar to the shoulders, stand, then dip and drive it overhead, splitting the legs to receive it.'],
            ['name' => 'Barbell Eccentric-Emphasis Deadlift', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Erector Spinae'], 'description' => 'Lift the barbell quickly, then lower it very slowly over 4-5 seconds to overload the negative phase.'],
            ['name' => 'Barbell Isometric Hold Squat (Bottom Position)', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Core'], 'description' => 'Squat down to parallel and hold the position for 10-30 seconds with the barbell on the back. Builds static strength and endurance.'],
            ['name' => 'Barbell 21s Biceps Curl', 'equipment' => 'Barbell', 'category_slug' => 'hypertrophy', 'target_muscles' => ['Biceps Brachii', 'Brachialis'], 'description' => 'Perform 7 bottom-half curls, 7 top-half curls, and 7 full-range curls without rest. High-intensity technique for arm growth.'],
            ['name' => 'Barbell Partial Deadlift (Top Half)', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Erector Spinae'], 'description' => 'Perform only the upper portion of the deadlift, from the knees to lockout. Overloads the glutes and upper back.'],
            ['name' => 'Barbell Narrow Stance Squat', 'equipment' => 'Barbell', 'category_slug' => 'isolation', 'target_muscles' => ['Quadriceps (Vastus Lateralis)', 'Glutes'], 'description' => 'Place feet close together, squat down while keeping the torso upright. Emphasises the outer quad sweep.'],
            ['name' => 'Barbell Wide Stance Squat', 'equipment' => 'Barbell', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Adductors', 'Quadriceps', 'Hamstrings'], 'description' => 'Take a wide stance with toes slightly out. Squat down, pushing knees outward to engage the inner thighs and glutes.'],
        ];

        $sourceDir = public_path('execises/barbel');
        $files = glob($sourceDir . '/*.png');
        sort($files);

        foreach ($execises as $i => $data) {
            $sourceFile = $files[$i] ?? null;

            if ($sourceFile) {
                $data['image'] = Storage::disk('public')->putFile('exercises', new File($sourceFile));
            }

            $categoryId = $categories[$data['category_slug']] ?? null;
            unset($data['category_slug']);
            $data['category_id'] = $categoryId;

            Exercise::create($data);
        }
    }
}
