<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\ExerciseCategory;
use Illuminate\Database\Seeder;

class BosuBallSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ExerciseCategory::pluck('id', 'slug');

        $execises = [
            ['name' => 'Bosu Squat (Dome Up)', 'equipment' => 'Bosu Ball', 'category_slug' => 'stability', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Stand on the dome with feet shoulder-width. Squat down while maintaining balance on the unstable surface, then return to standing. Engages core and stabilizers.'],
            ['name' => 'Bosu Squat (Platform Up)', 'equipment' => 'Bosu Ball', 'category_slug' => 'stability', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Stand on the flat platform side with the dome on the floor. Squat while balancing on the even more unstable surface. Advanced balance challenge.'],
            ['name' => 'Bosu Single-Leg Squat', 'equipment' => 'Bosu Ball', 'category_slug' => 'stability', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core', 'Balance'], 'description' => 'Stand on one leg on the dome. Squat down, keeping the knee aligned with the toes, then push back up. Intense unilateral stability and leg strength.'],
            ['name' => 'Bosu Lunge (Back Foot on Bosu)', 'equipment' => 'Bosu Ball', 'category_slug' => 'stability', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Place the rear foot on the dome (or flat side), front foot on the floor. Lower into a lunge, driving through the front heel to return. Challenges the stabilizing leg.'],
            ['name' => 'Bosu Split Squat (Front Foot on Bosu)', 'equipment' => 'Bosu Ball', 'category_slug' => 'stability', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Place the front foot on the dome, back foot on the floor. Squat down, keeping the front knee stable on the wobbly surface. High ankle and knee stability demand.'],
            ['name' => 'Bosu Push-Up (Dome Up)', 'equipment' => 'Bosu Ball', 'category_slug' => 'strength', 'target_muscles' => ['Pectoralis Major', 'Triceps', 'Anterior Deltoids', 'Core'], 'description' => 'Grip the sides of the platform with dome on the floor. Perform push-ups, lowering the chest toward the dome. Instability challenges the core and shoulders.'],
            ['name' => 'Bosu Push-Up (Platform Up)', 'equipment' => 'Bosu Ball', 'category_slug' => 'strength', 'target_muscles' => ['Pectoralis Major', 'Triceps', 'Anterior Deltoids', 'Core'], 'description' => 'Place hands on the flat platform, dome on the floor. Perform push-ups with the body parallel to the floor. The air-filled dome creates greater instability.'],
            ['name' => 'Bosu Pike Push-Up', 'equipment' => 'Bosu Ball', 'category_slug' => 'strength', 'target_muscles' => ['Anterior Deltoids', 'Triceps', 'Upper Pectorals', 'Core'], 'description' => 'Place feet on the floor, hands on the dome. Walk the hands closer to the feet so hips are high. Lower the head toward the dome, pressing back up. Shoulder-focused push-up.'],
            ['name' => 'Bosu Plank (Forearms on Dome)', 'equipment' => 'Bosu Ball', 'category_slug' => 'core', 'target_muscles' => ['Transverse Abdominis', 'Rectus Abdominis', 'Obliques', 'Shoulders'], 'description' => 'Place forearms on the dome, extend legs straight back. Hold a plank while keeping the Bosu steady. Excellent core and shoulder stabilizer work.'],
            ['name' => 'Bosu Plank (Hands on Dome)', 'equipment' => 'Bosu Ball', 'category_slug' => 'core', 'target_muscles' => ['Transverse Abdominis', 'Rectus Abdominis', 'Obliques', 'Shoulders'], 'description' => 'Place hands on the platform edge, dome down. Hold a straight-arm plank while balancing. Greater wrist and shoulder stability demand.'],
            ['name' => 'Bosu Plank Jacks', 'equipment' => 'Bosu Ball', 'category_slug' => 'cardio', 'target_muscles' => ['Core', 'Quadriceps', 'Glutes', 'Shoulders'], 'description' => 'In a plank with hands or forearms on the dome, jump the feet wide and back together like a jumping jack, keeping the hips stable.'],
            ['name' => 'Bosu Mountain Climbers', 'equipment' => 'Bosu Ball', 'category_slug' => 'cardio', 'target_muscles' => ['Quadriceps', 'Hip Flexors', 'Core', 'Shoulders'], 'description' => 'Place hands on the platform edge in a plank. Drive the knees alternately toward the chest rapidly, keeping the Bosu from wobbling.'],
            ['name' => 'Bosu Burpee', 'equipment' => 'Bosu Ball', 'category_slug' => 'cardio', 'target_muscles' => ['Full Body', 'Quadriceps', 'Glutes', 'Shoulders', 'Core'], 'description' => 'Hold the Bosu (platform edges), squat to place it on the floor, jump feet back into plank, perform a push-up on the Bosu, jump feet forward, stand and press the Bosu overhead (optional).'],
            ['name' => 'Bosu Hip Thrust (Shoulders on Bosu)', 'equipment' => 'Bosu Ball', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Core'], 'description' => 'Sit on the floor with upper back against the curved dome. Place a weight across the hips and thrust upward. The soft, unstable surface increases glute and core activation.'],
            ['name' => 'Bosu Glute Bridge (Feet on Dome)', 'equipment' => 'Bosu Ball', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Core'], 'description' => 'Lie on your back, place feet flat on the dome. Drive through the heels to lift the hips. The wobbling dome forces constant core and glute engagement.'],
            ['name' => 'Bosu Single-Leg Glute Bridge (Foot on Dome)', 'equipment' => 'Bosu Ball', 'category_slug' => 'stability', 'target_muscles' => ['Glutes', 'Hamstrings (unilateral)', 'Core'], 'description' => 'Place one foot on the dome, the other leg extended. Lift the hips, engaging the glutes. The unstable surface maximizes posterior chain activation.'],
            ['name' => 'Bosu Hamstring Curl (Heels on Dome)', 'equipment' => 'Bosu Ball', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Core'], 'description' => 'Lie on the back, heels on top of the dome. Lift the hips and roll the Bosu toward you by bending the knees, then slide back out. Constant hamstring tension.'],
            ['name' => 'Bosu Back Extension (Prone)', 'equipment' => 'Bosu Ball', 'category_slug' => 'strength', 'target_muscles' => ['Erector Spinae', 'Glutes', 'Hamstrings'], 'description' => 'Lie face down with the hips on the dome, feet against a wall or on the floor. Extend the spine to raise the chest, then lower. Lower back strengthening.'],
            ['name' => 'Bosu Deadlift (Single Leg)', 'equipment' => 'Bosu Ball', 'category_slug' => 'stability', 'target_muscles' => ['Hamstrings', 'Glutes', 'Core', 'Balance'], 'description' => 'Stand on one leg on the dome. Hinge forward, extending the free leg behind, keeping the standing knee slightly bent. Return to upright. High balance demand.'],
            ['name' => 'Bosu V-Up (Dome Up)', 'equipment' => 'Bosu Ball', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Obliques'], 'description' => 'Sit on the dome, lean back, and simultaneously raise the legs and upper body, balancing on the Bosu. Can pass a weight hand-to-foot. Intense core stability.'],
            ['name' => 'Bosu Russian Twist', 'equipment' => 'Bosu Ball', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis'], 'description' => 'Sit on the dome, feet off the floor, lean back slightly. Rotate the torso side to side holding a weight or hands together. The unstable seat forces constant core engagement.'],
            ['name' => 'Bosu Crunch (Dome Up)', 'equipment' => 'Bosu Ball', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Obliques'], 'description' => 'Sit on the dome with lower back supported, feet on the floor. Lie back and crunch upward, squeezing the abs. The curved dome supports the spine while increasing range of motion.'],
            ['name' => 'Bosu Oblique Crunch (Side Lying)', 'equipment' => 'Bosu Ball', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Quadratus Lumborum'], 'description' => 'Lie sideways with the hip against the dome, feet anchored. Crunch the torso upward laterally, targeting the obliques. Can also be done with legs.'],
            ['name' => 'Bosu Knee Tuck (Dome Up)', 'equipment' => 'Bosu Ball', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Transverse Abdominis'], 'description' => 'Start in a plank with hands on the floor, shins on the dome. Tuck the knees toward the chest, rolling the Bosu in. Extend back out. Intense core and shoulder workout.'],
            ['name' => 'Bosu Lateral Lunge (on Dome)', 'equipment' => 'Bosu Ball', 'category_slug' => 'stability', 'target_muscles' => ['Adductors', 'Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Stand beside the dome, step onto it with the near foot, bending that knee and sitting into the hip. Push off the dome to return. Targets inner thighs and stabilisers.'],
            ['name' => 'Bosu Jump Squat (Dome Up)', 'equipment' => 'Bosu Ball', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Calves', 'Core'], 'description' => 'Stand on the dome, squat slightly, then jump up explosively, landing softly back on the dome. The air-filled surface absorbs impact while challenging stability on landing.'],
            ['name' => 'Bosu Side-to-Side Jump (Lateral Hop)', 'equipment' => 'Bosu Ball', 'category_slug' => 'power', 'target_muscles' => ['Gluteus Medius', 'Quadriceps', 'Calves', 'Core'], 'description' => 'Stand beside the Bosu, jump laterally onto the dome, landing on one or both feet, then jump off to the other side. Develops lateral power and control.'],
            ['name' => 'Bosu Balance Stance (Single Leg)', 'equipment' => 'Bosu Ball', 'category_slug' => 'stability', 'target_muscles' => ['Core', 'Gluteus Medius', 'Calves', 'Ankle Stabilizers'], 'description' => 'Simply stand on one leg on the dome (or platform) and hold the balance for time. Foundational proprioception and ankle/knee stability exercise.'],
            ['name' => 'Bosu Push-Up to Side Plank', 'equipment' => 'Bosu Ball', 'category_slug' => 'core', 'target_muscles' => ['Pectorals', 'Triceps', 'Obliques', 'Transverse Abdominis'], 'description' => 'Perform a push-up on the Bosu, then rotate into a side plank, lifting one arm toward the ceiling. Returns to push-up and alternates. Dynamic core and upper body.'],
            ['name' => 'Bosu Calf Raise (Standing on Dome)', 'equipment' => 'Bosu Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Gastrocnemius', 'Soleus', 'Ankle Stabilizers'], 'description' => 'Stand on the dome with both feet. Raise the heels as high as possible, then lower. The unstable surface forces the ankles to work harder than on a flat step.'],
            ['name' => 'Bosu Triceps Dip', 'equipment' => 'Bosu Ball', 'category_slug' => 'strength', 'target_muscles' => ['Triceps', 'Anterior Deltoids', 'Pectorals'], 'description' => 'Sit on the edge of the platform side, hands next to hips. Slide off and lower the body by bending the elbows, then press back up. The dome facing down rocks, increasing core demand.'],
            ['name' => 'Bosu Hollow Body Hold (on Dome)', 'equipment' => 'Bosu Ball', 'category_slug' => 'core', 'target_muscles' => ['Transverse Abdominis', 'Rectus Abdominis', 'Hip Flexors'], 'description' => 'Lie on the dome with lower back pressed against it. Extend legs and arms, holding the hollow body position with the core tight. The dome forces constant micro-adjustments.'],
            ['name' => 'Bosu Pass Through (Legs)', 'equipment' => 'Bosu Ball', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Obliques'], 'description' => 'Lie on the back, hold the Bosu between hands and feet. Pass the Bosu from hands to feet by crunching up, then lower back down. Repeat the pass. Seamless core integration.'],
        ];

        foreach ($execises as $data) {
            Exercise::create([
                'name' => $data['name'],
                'equipment' => $data['equipment'],
                'category_id' => $categories[$data['category_slug']],
                'target_muscles' => $data['target_muscles'],
                'description' => $data['description'],
            ]);
        }
    }
}
