<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\ExerciseCategory;
use Illuminate\Database\Seeder;

class DipBeltSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ExerciseCategory::pluck('id', 'slug');

        $exercises = [
            ['name' => 'Weighted Dip Belt Dip', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Chest', 'Triceps', 'Anterior Deltoids', 'Core', 'Stabilizers'], 'description' => 'Attach weight to dip belt. Perform parallel bar dips. Added load increases upper body pressing intensity.'],
            ['name' => 'Weighted Dip Belt Pull-Up', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lats', 'Biceps', 'Rhomboids', 'Rear Deltoids', 'Core', 'Forearms'], 'description' => 'Attach weight to dip belt. Perform pull-ups. Increased resistance for back and biceps.'],
            ['name' => 'Weighted Dip Belt Chin-Up', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lats', 'Biceps', 'Rhomboids', 'Core', 'Forearms', 'Brachialis'], 'description' => 'Attach weight to dip belt. Perform chin-ups (supinated grip). Bicep-dominant pull with added load.'],
            ['name' => 'Weighted Dip Belt Wide Grip Pull-Up', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lats', 'Rhomboids', 'Teres Major', 'Rear Deltoids', 'Core', 'Forearms'], 'description' => 'Attach weight to dip belt. Wide grip pull-ups. Emphasizes lat width with added load.'],
            ['name' => 'Weighted Dip Belt Neutral Grip Pull-Up', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lats', 'Brachialis', 'Biceps', 'Core', 'Forearms', 'Rhomboids'], 'description' => 'Attach weight to dip belt. Neutral grip pull-ups. Joint-friendly back development with added weight.'],
            ['name' => 'Weighted Dip Belt Close Grip Pull-Up', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lats', 'Biceps', 'Core', 'Forearms', 'Rhomboids', 'Brachialis'], 'description' => 'Attach weight to dip belt. Close grip pull-ups. Emphasizes lower lats and biceps with added load.'],
            ['name' => 'Weighted Dip Belt Towel Pull-Up', 'equipment' => 'Dip Belt, Towel', 'category_slug' => 'strength', 'target_muscles' => ['Forearms', 'Grip Muscles', 'Lats', 'Biceps', 'Core', 'Rhomboids'], 'description' => 'Attach weight to dip belt. Wrap towel around bar. Perform pull-ups. Grip and forearm emphasis with added weight.'],
            ['name' => 'Weighted Dip Belt Muscle-Up', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lats', 'Chest', 'Triceps', 'Biceps', 'Core', 'Shoulders', 'Forearms'], 'description' => 'Attach weight to dip belt. Perform muscle-ups. Advanced full-body power with added resistance.'],
            ['name' => 'Weighted Dip Belt Ring Dip', 'equipment' => 'Dip Belt, Gymnastic Rings', 'category_slug' => 'strength', 'target_muscles' => ['Chest', 'Triceps', 'Biceps', 'Core', 'Shoulder Stabilizers', 'Traps'], 'description' => 'Attach weight to dip belt. Perform ring dips. Unstable ring dips with added load.'],
            ['name' => 'Weighted Dip Belt Ring Pull-Up', 'equipment' => 'Dip Belt, Gymnastic Rings', 'category_slug' => 'strength', 'target_muscles' => ['Lats', 'Biceps', 'Core', 'Forearms', 'Rhomboids', 'Shoulder Stabilizers'], 'description' => 'Attach weight to dip belt. Perform ring pull-ups. Unstable ring pull with added resistance.'],
            ['name' => 'Weighted Dip Belt Bar Dips (Triceps Focus)', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Triceps', 'Anterior Deltoids', 'Core', 'Chest', 'Stabilizers'], 'description' => 'Attach weight to dip belt. Upright triceps-focused dips. Emphasizes triceps with added load.'],
            ['name' => 'Weighted Dip Belt Leaning Forward Dips (Chest Focus)', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Chest (Lower)', 'Triceps', 'Anterior Deltoids', 'Core', 'Stabilizers'], 'description' => 'Attach weight to dip belt. Lean forward chest-focused dips. Emphasizes lower chest with added weight.'],
            ['name' => 'Weighted Dip Belt L-Sit Dip', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Chest', 'Triceps', 'Core (Rectus Abdominis, Hip Flexors)', 'Shoulders'], 'description' => 'Attach weight to dip belt. Perform dips while holding L-sit. Core and upper body with added load.'],
            ['name' => 'Weighted Dip Belt Bulgarian Dip', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Triceps', 'Chest', 'Core', 'Stabilizers', 'Biceps', 'Shoulders'], 'description' => 'Attach weight to dip belt. Perform Bulgarian dips (hands on rings/bars, elbows flared). Added load.'],
            ['name' => 'Weighted Dip Belt Russian Dip', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Chest', 'Triceps', 'Core', 'Shoulders', 'Stabilizers', 'Forearms'], 'description' => 'Attach weight to dip belt. Russian dip variation. Advanced pressing with added resistance.'],
            ['name' => 'Weighted Dip Belt Negative Dip (Eccentric)', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Chest', 'Triceps', 'Anterior Deltoids', 'Core', 'Stabilizers'], 'description' => 'Attach weight to dip belt. Lower slowly (3-5 sec) from top to bottom. Eccentric overload with added weight.'],
            ['name' => 'Weighted Dip Belt Negative Pull-Up (Eccentric)', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lats', 'Biceps', 'Rhomboids', 'Core', 'Forearms', 'Rear Deltoids'], 'description' => 'Attach weight to dip belt. Jump to top, lower slowly. Eccentric back strength with added load.'],
            ['name' => 'Weighted Dip Belt Isometric Hold (Dip Bottom)', 'equipment' => 'Dip Belt', 'category_slug' => 'core', 'target_muscles' => ['Chest', 'Triceps', 'Core', 'Shoulders', 'Stabilizers', 'Forearms'], 'description' => 'Attach weight to dip belt. Hold bottom dip position. Static pressing endurance with added load.'],
            ['name' => 'Weighted Dip Belt Isometric Hold (Pull-Up Top)', 'equipment' => 'Dip Belt', 'category_slug' => 'core', 'target_muscles' => ['Lats', 'Biceps', 'Core', 'Forearms', 'Rhomboids', 'Traps'], 'description' => 'Attach weight to dip belt. Hold top pull-up position. Static pulling endurance with added load.'],
            ['name' => 'Weighted Dip Belt Isometric Hold (Pull-Up Mid)', 'equipment' => 'Dip Belt', 'category_slug' => 'core', 'target_muscles' => ['Lats', 'Biceps', 'Core', 'Forearms', 'Rhomboids', 'Traps'], 'description' => 'Attach weight to dip belt. Hold mid pull-up position. Static back endurance with added load.'],
            ['name' => 'Weighted Dip Belt Slow Tempo Dip (3-1-3)', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Chest', 'Triceps', 'Anterior Deltoids', 'Core', 'Stabilizers'], 'description' => 'Attach weight to dip belt. 3 sec down, 1 sec hold, 3 sec up. Time under tension with added load.'],
            ['name' => 'Weighted Dip Belt Slow Tempo Pull-Up (3-1-3)', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lats', 'Biceps', 'Rhomboids', 'Core', 'Forearms', 'Rear Deltoids'], 'description' => 'Attach weight to dip belt. 3 sec up, 1 sec hold, 3 sec down. Time under tension pulling with added weight.'],
            ['name' => 'Weighted Dip Belt One-Arm Dip (Assisted)', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Chest', 'Triceps', 'Core', 'Obliques', 'Shoulders', 'Stabilizers'], 'description' => 'Attach weight to dip belt. Perform one-arm dip with other arm assisting. Unilateral pressing with added load.'],
            ['name' => 'Weighted Dip Belt One-Arm Pull-Up (Assisted)', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lats', 'Biceps', 'Core', 'Obliques', 'Forearms', 'Rhomboids'], 'description' => 'Attach weight to dip belt. One-arm pull-up with other arm assisting. Unilateral pulling with added load.'],
            ['name' => 'Weighted Dip Belt Sit-Up', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Core', 'Obliques', 'Quadriceps'], 'description' => 'Attach weight to dip belt around waist. Perform sit-ups. Added core resistance.'],
            ['name' => 'Weighted Dip Belt Leg Raise (Hanging)', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lower Abs', 'Hip Flexors', 'Core', 'Iliopsoas', 'Quadriceps'], 'description' => 'Attach weight to dip belt around waist or ankles. Perform hanging leg raises. Added lower ab resistance.'],
            ['name' => 'Weighted Dip Belt Knee Raise (Hanging)', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lower Abs', 'Hip Flexors', 'Core', 'Iliopsoas', 'Rectus Abdominis'], 'description' => 'Attach weight to dip belt around waist. Perform hanging knee raises. Added core resistance.'],
            ['name' => 'Weighted Dip Belt Toes-to-Bar', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Core (Lower Abs)', 'Hip Flexors', 'Lats', 'Obliques', 'Shoulders'], 'description' => 'Attach weight to dip belt. Hang and lift toes to bar. Advanced core with added load.'],
            ['name' => 'Weighted Dip Belt Windshield Wiper', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Core (Obliques)', 'Hip Flexors', 'Lats', 'Shoulders', 'Stabilizers'], 'description' => 'Attach weight to dip belt. Hang with legs straight, rotate side to side. Oblique work with added resistance.'],
            ['name' => 'Weighted Dip Belt L-Sit Hold', 'equipment' => 'Dip Belt', 'category_slug' => 'core', 'target_muscles' => ['Core (Rectus Abdominis, Hip Flexors)', 'Triceps', 'Shoulders', 'Quads'], 'description' => 'Attach weight to dip belt. Hold L-sit on bars or rings. Core endurance with added load.'],
            ['name' => 'Weighted Dip Belt V-Sit Hold', 'equipment' => 'Dip Belt', 'category_slug' => 'core', 'target_muscles' => ['Core (Entire)', 'Hip Flexors', 'Triceps', 'Shoulders', 'Hamstrings'], 'description' => 'Attach weight to dip belt. Hold V-sit position. Advanced core strength with added resistance.'],
            ['name' => 'Weighted Dip Belt Skin the Cat', 'equipment' => 'Dip Belt, Gymnastic Rings/Bars', 'category_slug' => 'strength', 'target_muscles' => ['Shoulders', 'Lats', 'Core', 'Biceps', 'Chest', 'Forearms'], 'description' => 'Attach weight to dip belt. Perform skin the cat with added resistance. Advanced mobility and strength.'],
            ['name' => 'Weighted Dip Belt Front Lever Hold', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lats', 'Core (Entire)', 'Glutes', 'Hamstrings', 'Shoulders', 'Forearms'], 'description' => 'Attach weight to dip belt. Hold front lever position. Extreme lat and core strength with added load.'],
            ['name' => 'Weighted Dip Belt Back Lever Hold', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lower Back', 'Lats', 'Glutes', 'Hamstrings', 'Shoulders', 'Core'], 'description' => 'Attach weight to dip belt. Hold back lever position. Advanced calisthenics hold with added resistance.'],
            ['name' => 'Weighted Dip Belt Planche Lean (On Bars)', 'equipment' => 'Dip Belt, Bars', 'category_slug' => 'strength', 'target_muscles' => ['Shoulders', 'Chest', 'Core', 'Biceps', 'Triceps', 'Hip Flexors'], 'description' => 'Attach weight to dip belt. Perform planche lean on bars. Planche progression with added load.'],
            ['name' => 'Weighted Dip Belt Advanced Tuck Planche', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Shoulders', 'Chest', 'Core', 'Triceps', 'Hip Flexors', 'Forearms'], 'description' => 'Attach weight to dip belt. Hold advanced tuck planche. Planche progression with added resistance.'],
            ['name' => 'Weighted Dip Belt Straddle Planche', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Shoulders', 'Chest', 'Core', 'Adductors', 'Triceps', 'Hip Flexors'], 'description' => 'Attach weight to dip belt. Hold straddle planche. Advanced planche progression with added load.'],
            ['name' => 'Weighted Dip Belt Muscle-Up Transition', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lats', 'Chest', 'Triceps', 'Core', 'Shoulders', 'Biceps', 'Forearms'], 'description' => 'Attach weight to dip belt. Perform muscle-up transition only. Skill-specific strength with added resistance.'],
            ['name' => 'Weighted Dip Belt False Grip Pull-Up', 'equipment' => 'Dip Belt', 'category_slug' => 'strength', 'target_muscles' => ['Lats', 'Biceps', 'Forearms', 'Core', 'Rhomboids', 'Brachialis'], 'description' => 'Attach weight to dip belt. Perform false grip pull-ups. Prepares for muscle-ups with added load.'],
        ];

        foreach ($exercises as $data) {
            Exercise::create([
                'name' => $data['name'],
                'equipment' => $data['equipment'],
                'category_id' => $categories[$data['category_slug']],
                'target_muscles' => $data['target_muscles'],
                'description' => $data['description'],
            ]);
        }
    }
}
