<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\ExerciseCategory;
use Illuminate\Database\Seeder;

class DumbbellSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ExerciseCategory::pluck('id', 'slug');

        $execises = [
            [
                'name' => 'Dumbbell Bench Press (Flat)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids', 'Triceps'],
                'description' => 'Lie on a flat bench, press dumbbells from chest level to full arm extension with palms facing forward, then lower with control.',
            ],
            [
                'name' => 'Dumbbell Bench Press (Incline)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Upper Pectoralis', 'Anterior Deltoids', 'Triceps'],
                'description' => 'Set bench to 30-45 incline, press dumbbells from upper chest to lockout, emphasizing the clavicular head of the chest.',
            ],
            [
                'name' => 'Dumbbell Bench Press (Decline)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Lower Pectoralis', 'Anterior Deltoids', 'Triceps'],
                'description' => 'On a decline bench, press dumbbells from lower sternum to full extension, targeting the lower chest fibers.',
            ],
            [
                'name' => 'Dumbbell Flyes (Flat)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids'],
                'description' => 'Lie flat, dumbbells above chest with slight elbow bend, lower them in a wide arc until a deep stretch is felt, then squeeze back together.',
            ],
            [
                'name' => 'Dumbbell Flyes (Incline)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Upper Pectoralis', 'Anterior Deltoids'],
                'description' => 'Perform on an incline bench, opening the arms wide and bringing dumbbells together in an arc, isolating the upper chest.',
            ],
            [
                'name' => 'Dumbbell Flyes (Decline)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Lower Pectoralis', 'Anterior Deltoids'],
                'description' => 'On a decline bench, lower dumbbells out to the sides in an arc, squeezing the lower chest at the bottom of the movement.',
            ],
            [
                'name' => 'Dumbbell Squeeze Press (Hex Press)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'hypertrophy',
                'target_muscles' => ['Inner Pectoralis', 'Triceps'],
                'description' => 'Press the dumbbells together tightly throughout the movement, palms facing each other. Emphasizes inner chest contraction.',
            ],
            [
                'name' => 'Dumbbell Pullover',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Latissimus Dorsi', 'Pectoralis Major', 'Serratus Anterior', 'Triceps Long Head'],
                'description' => 'Lie across a bench with upper back supported, extend a dumbbell overhead and pull it over the chest in an arc, feeling the stretch in lats and chest.',
            ],
            [
                'name' => 'Single-Arm Dumbbell Bench Press',
                'equipment' => 'Dumbbell',
                'category_slug' => 'stability',
                'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids', 'Triceps', 'Core'],
                'description' => 'Press one dumbbell at a time while the other arm remains stationary. Challenges core anti-rotation and addresses imbalances.',
            ],
            [
                'name' => 'Alternating Dumbbell Bench Press',
                'equipment' => 'Dumbbell',
                'category_slug' => 'stability',
                'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids', 'Triceps', 'Core'],
                'description' => 'Press dumbbells one arm at a time in a seesaw pattern, keeping the non-working side locked out.',
            ],
            [
                'name' => 'Dumbbell Seated Overhead Press',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps'],
                'description' => 'Sit on a bench with back support, press dumbbells from shoulder height to overhead lockout with palms facing forward.',
            ],
            [
                'name' => 'Dumbbell Arnold Press',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Rotator Cuff'],
                'description' => 'Start with palms facing you at chin height, rotate palms outward while pressing overhead, reverse on the way down. Engages all deltoid heads.',
            ],
            [
                'name' => 'Dumbbell Lateral Raise',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Medial Deltoids', 'Supraspinatus'],
                'description' => 'Stand with dumbbells at sides, raise arms out to the sides to shoulder height with a slight lean forward, then lower with control.',
            ],
            [
                'name' => 'Dumbbell Front Raise',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Anterior Deltoids', 'Pectoralis Minor'],
                'description' => 'Hold dumbbells in front of thighs, raise one or both straight forward to shoulder height, then lower slowly.',
            ],
            [
                'name' => 'Dumbbell Bent-Over Lateral Raise',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Rear Deltoids', 'Rhomboids', 'Infraspinatus'],
                'description' => 'Hinge at the hips with a flat back, dumbbells hanging down, raise them out to the sides until arms are parallel to the floor, squeeze shoulder blades.',
            ],
            [
                'name' => 'Dumbbell Upright Row',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Medial Deltoids', 'Upper Traps', 'Biceps'],
                'description' => 'Hold dumbbells in front of thighs, pull them up the body to chin height, leading with the elbows.',
            ],
            [
                'name' => 'Dumbbell Shrug',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Upper Trapezius', 'Levator Scapulae'],
                'description' => 'Hold heavy dumbbells at sides, shrug shoulders up toward ears, hold and squeeze, then lower.',
            ],
            [
                'name' => 'Dumbbell Bent-Over Row (Single-Arm)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Biceps', 'Rear Deltoids', 'Erector Spinae'],
                'description' => 'Place one knee and hand on a bench, pull a dumbbell from a dead hang to the side of the torso, squeezing the back.',
            ],
            [
                'name' => 'Dumbbell Bent-Over Row (Both Arms)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Traps', 'Biceps', 'Erector Spinae'],
                'description' => 'Hinge forward with a flat back, hold dumbbells below shoulders, row both dumbbells to the hips simultaneously.',
            ],
            [
                'name' => 'Dumbbell Chest-Supported Row',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Middle Traps', 'Rear Deltoids', 'Biceps'],
                'description' => 'Lie face-down on an incline bench, row dumbbells to the sides of the chest, eliminating lower back strain.',
            ],
            [
                'name' => 'Dumbbell Renegade Row',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Biceps', 'Core', 'Shoulders'],
                'description' => 'Start in a push-up position on dumbbells, row one dumbbell to the hip while stabilizing the body with the other arm.',
            ],
            [
                'name' => 'Dumbbell Pullover (Bent-Arm)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Latissimus Dorsi', 'Pectoralis Major', 'Serratus', 'Triceps'],
                'description' => 'Lie across a bench, hold a dumbbell overhead with bent elbows, pull it to the chest in a pullover motion.',
            ],
            [
                'name' => 'Dumbbell Biceps Curl (Standing)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Biceps Brachii', 'Brachialis'],
                'description' => 'Stand with dumbbells at sides, palms forward, curl the weights up by flexing elbows, squeeze at top, lower with control.',
            ],
            [
                'name' => 'Dumbbell Hammer Curl',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Biceps', 'Brachialis', 'Brachioradialis'],
                'description' => 'Perform curls with a neutral grip (palms facing each other), emphasizing the brachialis and forearm.',
            ],
            [
                'name' => 'Dumbbell Incline Curl',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Biceps Brachii (long head emphasis)'],
                'description' => 'Lie back on an incline bench, arms hanging straight down, curl dumbbells up, stretching the long head.',
            ],
            [
                'name' => 'Dumbbell Concentration Curl',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Biceps Brachii', 'Brachialis'],
                'description' => 'Sit on a bench, brace the back of one upper arm against the inner thigh, curl the dumbbell in a controlled manner.',
            ],
            [
                'name' => 'Dumbbell Preacher Curl',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Biceps Brachii', 'Brachialis'],
                'description' => 'Using a preacher bench, curl one or both dumbbells with the upper arm supported, focusing on strict form.',
            ],
            [
                'name' => 'Dumbbell Reverse Curl',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Brachioradialis', 'Wrist Extensors', 'Biceps'],
                'description' => 'Stand with palms facing down (pronated grip), curl the dumbbells up by flexing elbows, leading with the knuckles.',
            ],
            [
                'name' => 'Dumbbell Zottman Curl',
                'equipment' => 'Dumbbell',
                'category_slug' => 'hypertrophy',
                'target_muscles' => ['Biceps', 'Brachialis', 'Forearms'],
                'description' => 'Curl with palms up, at the top rotate to palms down, then lower with a reverse grip. Works biceps and brachioradialis.',
            ],
            [
                'name' => 'Dumbbell Drag Curl',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Biceps Brachii', 'Brachialis'],
                'description' => 'Stand and let the dumbbells slide up the front of the body, elbows moving back slightly, keeping constant tension on biceps.',
            ],
            [
                'name' => 'Dumbbell Overhead Triceps Extension (Single Dumbbell)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Triceps Brachii (long head)', 'All Heads'],
                'description' => 'Hold one dumbbell with both hands overhead, lower it behind the head by bending elbows, then extend back up.',
            ],
            [
                'name' => 'Dumbbell Overhead Triceps Extension (Two Dumbbells)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Triceps Brachii'],
                'description' => 'Sit or stand with a dumbbell in each hand, arms extended overhead, lower the dumbbells behind the neck, then extend.',
            ],
            [
                'name' => 'Dumbbell Triceps Kickback',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Triceps Brachii (lateral and medial heads)'],
                'description' => 'Hinge forward, upper arm parallel to the floor, extend the dumbbell straight back, squeezing the triceps at full extension.',
            ],
            [
                'name' => 'Dumbbell French Press (Lying Triceps Extension)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Triceps Brachii'],
                'description' => 'Lie on a bench, hold dumbbells above chest, lower them toward the forehead by bending elbows, then press back up.',
            ],
            [
                'name' => 'Dumbbell Tate Press',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Triceps Brachii (long head)', 'Lower Pectorals'],
                'description' => 'Lie on a bench, dumbbells at chest with elbows out, press them together and up, squeezing triceps.',
            ],
            [
                'name' => 'Dumbbell Goblet Squat',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'],
                'description' => 'Hold one dumbbell vertically against your chest with both hands, squat down keeping the torso upright, then drive back up.',
            ],
            [
                'name' => 'Dumbbell Front Squat (Two Dumbbells)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core', 'Upper Back'],
                'description' => 'Rest a dumbbell on each shoulder with elbows high, perform a squat while maintaining an upright torso.',
            ],
            [
                'name' => 'Dumbbell Split Squat',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'],
                'description' => 'Hold dumbbells at sides, stand in a staggered stance, lower until back knee nearly touches the ground, then push up.',
            ],
            [
                'name' => 'Dumbbell Bulgarian Split Squat',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'],
                'description' => 'Elevate rear foot on a bench, hold dumbbells at sides, squat down with the front leg, driving through the front heel.',
            ],
            [
                'name' => 'Dumbbell Reverse Lunge',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'],
                'description' => 'Holding dumbbells, step backward into a lunge, lower until both knees reach 90, then push off the front foot to return.',
            ],
            [
                'name' => 'Dumbbell Forward Lunge',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'],
                'description' => 'With dumbbells at sides, step forward into a lunge, lower and return to starting position by pushing through the front foot.',
            ],
            [
                'name' => 'Dumbbell Walking Lunge',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'],
                'description' => 'Carry dumbbells and walk forward in alternating lunges, maintaining an upright torso throughout.',
            ],
            [
                'name' => 'Dumbbell Step-Up',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'],
                'description' => 'Holding dumbbells, step onto a box or bench with one leg, drive through the heel to stand up, then lower back down.',
            ],
            [
                'name' => 'Dumbbell Romanian Deadlift',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Hamstrings', 'Glutes', 'Erector Spinae'],
                'description' => 'Hold dumbbells in front of thighs, hinge at the hips with a slight knee bend, lower dumbbells along the legs, then return by extending hips.',
            ],
            [
                'name' => 'Dumbbell Stiff-Leg Deadlift',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Hamstrings', 'Glutes', 'Erector Spinae'],
                'description' => 'Keep legs nearly straight, push hips back, lower dumbbells to mid-shin, feeling a stretch in hamstrings, then stand up.',
            ],
            [
                'name' => 'Dumbbell Single-Leg Deadlift',
                'equipment' => 'Dumbbell',
                'category_slug' => 'stability',
                'target_muscles' => ['Hamstrings', 'Glutes', 'Core'],
                'description' => 'Hold dumbbells in one or both hands, stand on one leg, hinge forward while extending the free leg behind, return to standing.',
            ],
            [
                'name' => 'Dumbbell Glute Bridge (Weighted)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Glutes', 'Hamstrings'],
                'description' => 'Lie on your back, place a dumbbell across your hips, drive through the heels to lift hips until body forms a straight line, squeeze glutes.',
            ],
            [
                'name' => 'Dumbbell Hip Thrust',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Glutes', 'Hamstrings', 'Core'],
                'description' => 'Sit on floor, upper back against a bench, dumbbell across hips, thrust hips upward to full extension, squeezing glutes at the top.',
            ],
            [
                'name' => 'Dumbbell Calf Raise (Standing)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Gastrocnemius', 'Soleus'],
                'description' => 'Hold dumbbells at sides, balls of feet on a block, raise heels as high as possible, then lower for a full stretch.',
            ],
            [
                'name' => 'Dumbbell Calf Raise (Seated)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Soleus', 'Gastrocnemius'],
                'description' => 'Sit on a bench, place dumbbells on thighs just above knees, perform calf raises by extending ankles.',
            ],
            [
                'name' => 'Dumbbell Farmers Walk',
                'equipment' => 'Dumbbell',
                'category_slug' => 'endurance',
                'target_muscles' => ['Forearms', 'Traps', 'Core', 'Quadriceps', 'Glutes'],
                'description' => 'Hold heavy dumbbells at sides, walk for a set distance or time while maintaining posture and a tight grip.',
            ],
            [
                'name' => 'Dumbbell Suitcase Carry',
                'equipment' => 'Dumbbell',
                'category_slug' => 'stability',
                'target_muscles' => ['Obliques', 'Core', 'Forearms', 'Traps'],
                'description' => 'Carry a heavy dumbbell in one hand like a suitcase, walk without leaning to the side, engaging the obliques to stay upright.',
            ],
            [
                'name' => 'Dumbbell Clean',
                'equipment' => 'Dumbbell',
                'category_slug' => 'power',
                'target_muscles' => ['Quadriceps', 'Glutes', 'Traps', 'Biceps', 'Deltoids', 'Core'],
                'description' => 'Start with a dumbbell between feet, explosively extend hips and knees, shrug and pull the dumbbell to the shoulder, catch in a front rack.',
            ],
            [
                'name' => 'Dumbbell Power Clean',
                'equipment' => 'Dumbbell',
                'category_slug' => 'power',
                'target_muscles' => ['Quadriceps', 'Hamstrings', 'Glutes', 'Shoulders', 'Traps', 'Core'],
                'description' => 'Perform a clean from the floor to shoulders with a powerful triple extension, catching the dumbbells without a full squat.',
            ],
            [
                'name' => 'Dumbbell Snatch',
                'equipment' => 'Dumbbell',
                'category_slug' => 'power',
                'target_muscles' => ['Glutes', 'Hamstrings', 'Shoulders', 'Triceps', 'Core'],
                'description' => 'In one explosive motion, pull a dumbbell from the floor to overhead, catching it with locked elbow and extended hips.',
            ],
            [
                'name' => 'Dumbbell Thruster',
                'equipment' => 'Dumbbell',
                'category_slug' => 'power',
                'target_muscles' => ['Quadriceps', 'Glutes', 'Deltoids', 'Triceps', 'Core'],
                'description' => 'Hold dumbbells at shoulders, squat down, then drive up explosively and press the dumbbells overhead in one fluid motion.',
            ],
            [
                'name' => 'Dumbbell Devils Press',
                'equipment' => 'Dumbbell',
                'category_slug' => 'power',
                'target_muscles' => ['Hamstrings', 'Shoulders', 'Triceps', 'Core'],
                'description' => 'Start in a burpee position with hands on dumbbells, kick legs back, then jump feet forward, clean the dumbbells, and press overhead.',
            ],
            [
                'name' => 'Dumbbell Man Maker',
                'equipment' => 'Dumbbell',
                'category_slug' => 'power',
                'target_muscles' => ['Chest', 'Back', 'Legs', 'Shoulders', 'Core'],
                'description' => 'Perform a push-up on dumbbells, row one dumbbell in each hand while in plank, jump feet forward, then clean and press overhead. One rep.',
            ],
            [
                'name' => 'Dumbbell Turkish Get-Up',
                'equipment' => 'Dumbbell',
                'category_slug' => 'mobility',
                'target_muscles' => ['Shoulders', 'Core', 'Glutes', 'Hamstrings', 'Rotator Cuff'],
                'description' => 'Lie on your back holding a dumbbell overhead, stand up by moving through a series of positions while keeping the dumbbell stable overhead, then reverse.',
            ],
            [
                'name' => 'Dumbbell Russian Twist',
                'equipment' => 'Dumbbell',
                'category_slug' => 'core',
                'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis'],
                'description' => 'Sit on the floor with knees bent, lean back slightly holding a dumbbell, rotate the torso side to side.',
            ],
            [
                'name' => 'Dumbbell Weighted Crunch',
                'equipment' => 'Dumbbell',
                'category_slug' => 'core',
                'target_muscles' => ['Rectus Abdominis', 'Obliques'],
                'description' => 'Lie on your back, hold a dumbbell against the chest or overhead, curl the torso up by contracting the abs.',
            ],
            [
                'name' => 'Dumbbell Side Bend',
                'equipment' => 'Dumbbell',
                'category_slug' => 'core',
                'target_muscles' => ['Obliques', 'Quadratus Lumborum'],
                'description' => 'Stand holding a dumbbell in one hand at your side, bend laterally at the waist toward the dumbbell, then return upright.',
            ],
            [
                'name' => 'Dumbbell Woodchop',
                'equipment' => 'Dumbbell',
                'category_slug' => 'core',
                'target_muscles' => ['Obliques', 'Transverse Abdominis', 'Rectus Abdominis'],
                'description' => 'Hold a dumbbell with both hands, perform a diagonal chopping motion from high to low across the body, rotating the torso.',
            ],
            [
                'name' => 'Dumbbell Leg Raise (with Dumbbell between feet)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'core',
                'target_muscles' => ['Lower Rectus Abdominis', 'Hip Flexors'],
                'description' => 'Lie on a bench, hold a dumbbell between your feet, lift your legs until they are vertical or higher, then lower with control.',
            ],
            [
                'name' => 'Dumbbell Wrist Curl (Palms Up)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Forearm Flexors'],
                'description' => 'Rest forearms on thighs or a bench, palms up, curl the dumbbell by flexing the wrists only.',
            ],
            [
                'name' => 'Dumbbell Reverse Wrist Curl (Palms Down)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Forearm Extensors'],
                'description' => 'Forearms supported, palms down, extend the wrists upward against resistance, then lower.',
            ],
            [
                'name' => 'Dumbbell Finger Curl',
                'equipment' => 'Dumbbell',
                'category_slug' => 'isolation',
                'target_muscles' => ['Forearm Flexors', 'Grip'],
                'description' => 'Let the dumbbell roll down the fingers, then curl the fingers to bring it back into the palm, working grip strength.',
            ],
            [
                'name' => 'Dumbbell Pause Bench Press',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'],
                'description' => 'At the bottom of the dumbbell press, pause for 1-2 seconds, then press up explosively. Eliminates momentum.',
            ],
            [
                'name' => 'Dumbbell Eccentric-Emphasis Curl',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Biceps Brachii', 'Brachialis'],
                'description' => 'Curl the dumbbell up quickly, then take 3-5 seconds to lower it. Focuses on the negative phase.',
            ],
            [
                'name' => 'Dumbbell Tempo Goblet Squat (3-1-3)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'hypertrophy',
                'target_muscles' => ['Quadriceps', 'Glutes', 'Core'],
                'description' => '3 seconds down, 1-second pause at the bottom, 3 seconds up. Maximizes time under tension.',
            ],
            [
                'name' => 'Dumbbell Isometric Lateral Raise Hold',
                'equipment' => 'Dumbbell',
                'category_slug' => 'strength',
                'target_muscles' => ['Medial Deltoids', 'Supraspinatus'],
                'description' => 'Hold dumbbells at the top of a lateral raise for 10-30 seconds, maintaining constant tension.',
            ],
            [
                'name' => 'Dumbbell Explosive Push Press',
                'equipment' => 'Dumbbell',
                'category_slug' => 'power',
                'target_muscles' => ['Deltoids', 'Triceps', 'Quadriceps', 'Core'],
                'description' => 'Dip slightly at the knees, then explode upward, pressing the dumbbells overhead using leg drive.',
            ],
            [
                'name' => 'Dumbbell 21s (Biceps Curl)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'hypertrophy',
                'target_muscles' => ['Biceps Brachii', 'Brachialis'],
                'description' => '7 reps bottom half, 7 reps top half, 7 full range reps without rest.',
            ],
            [
                'name' => 'Dumbbell Partial Reps (Top Half Lateral Raise)',
                'equipment' => 'Dumbbell',
                'category_slug' => 'hypertrophy',
                'target_muscles' => ['Medial Deltoids'],
                'description' => 'Only perform lateral raises from the midpoint to shoulder height, keeping constant tension.',
            ],
        ];

        foreach ($execises as $data) {
            $categoryId = $categories[$data['category_slug']] ?? null;
            unset($data['category_slug']);
            $data['category_id'] = $categoryId;

            Exercise::create($data);
        }
    }
}
