<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\ExerciseCategory;
use Illuminate\Database\Seeder;

class MedicineBallSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ExerciseCategory::pluck('id', 'slug');

        $exercises = [
            ['name' => 'Medicine Ball Chest Pass (Standing)', 'equipment' => 'Medicine Ball', 'category_slug' => 'power', 'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids', 'Triceps', 'Core'], 'description' => 'Stand facing a wall or partner, hold the ball at chest level, and explosively push it forward with both hands, extending arms fully. Catch and repeat.'],
            ['name' => 'Medicine Ball Overhead Throw', 'equipment' => 'Medicine Ball', 'category_slug' => 'power', 'target_muscles' => ['Anterior Deltoids', 'Triceps', 'Latissimus Dorsi', 'Core', 'Quadriceps'], 'description' => 'Stand holding the ball overhead, step forward and throw it forcefully against the ground or to a partner, engaging the lats and core to generate power.'],
            ['name' => 'Medicine Ball Scoop Toss', 'equipment' => 'Medicine Ball', 'category_slug' => 'power', 'target_muscles' => ['Glutes', 'Hamstrings', 'Quadriceps', 'Shoulders', 'Core'], 'description' => 'Squat holding the ball between legs, then explosively extend hips and knees to throw the ball upward and backward over the head, as if tossing behind you.'],
            ['name' => 'Medicine Ball Rotational Throw (Side Throw)', 'equipment' => 'Medicine Ball', 'category_slug' => 'power', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Shoulders', 'Hips', 'Quadriceps'], 'description' => 'Stand sideways to a wall, hold the ball at hip level, rotate the torso away, then explosively twist and throw the ball against the wall, catching on rebound.'],
            ['name' => 'Medicine Ball Slam (Overhead)', 'equipment' => 'Medicine Ball', 'category_slug' => 'power', 'target_muscles' => ['Latissimus Dorsi', 'Triceps', 'Abdominals', 'Quadriceps', 'Glutes'], 'description' => 'Rise onto toes, lift the ball overhead, then forcefully slam it to the ground, squatting slightly to catch the bounce. Repeat rapidly.'],
            ['name' => 'Medicine Ball Side Slam', 'equipment' => 'Medicine Ball', 'category_slug' => 'power', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Latissimus Dorsi', 'Glutes'], 'description' => 'Hold the ball at one hip, rotate the torso to the opposite side, then explosively slam the ball to the ground beside the opposite foot. Alternate sides.'],
            ['name' => 'Medicine Ball Rainbow Slam', 'equipment' => 'Medicine Ball', 'category_slug' => 'power', 'target_muscles' => ['Obliques', 'Latissimus Dorsi', 'Shoulders', 'Core'], 'description' => 'Lift the ball from one hip, arc it overhead like a rainbow, and slam it down to the other side. Focuses on rotational power.'],
            ['name' => 'Medicine Ball Wall Ball', 'equipment' => 'Medicine Ball', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Shoulders', 'Triceps', 'Core'], 'description' => 'Stand facing a wall, squat holding the ball at chest, drive up and throw the ball to a target on the wall, catch in squat and repeat.'],
            ['name' => 'Medicine Ball Woodchop (High-to-Low)', 'equipment' => 'Medicine Ball', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Transverse Abdominis', 'Rectus Abdominis', 'Shoulders'], 'description' => 'Hold the ball overhead to one side, chop diagonally across the body to the opposite hip, rotating the torso, then return controlled.'],
            ['name' => 'Medicine Ball Woodchop (Low-to-High)', 'equipment' => 'Medicine Ball', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Transverse Abdominis', 'Rectus Abdominis', 'Shoulders'], 'description' => 'Start with ball at one hip, pull it upward diagonally across the body to the opposite overhead position, engaging the core.'],
            ['name' => 'Medicine Ball Russian Twist', 'equipment' => 'Medicine Ball', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis'], 'description' => 'Sit with knees bent, lean back, hold the ball with both hands, and rotate the torso side to side, tapping the ball on the floor each rep.'],
            ['name' => 'Medicine Ball Seated Russian Twist with Toss', 'equipment' => 'Medicine Ball', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis', 'Hip Flexors'], 'description' => 'Sit in a V-position, rotate and lightly toss the ball to the opposite side, catch, and repeat. Increases dynamic control.'],
            ['name' => 'Medicine Ball Sit-Up and Throw', 'equipment' => 'Medicine Ball', 'category_slug' => 'power', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Anterior Deltoids', 'Triceps'], 'description' => 'Lie on your back with ball overhead, perform a sit-up, and at the top explosively throw the ball against a wall or to a partner. Catch and repeat.'],
            ['name' => 'Medicine Ball V-Up', 'equipment' => 'Medicine Ball', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Obliques'], 'description' => 'Lie flat, hold the ball between hands and feet (or hands only), simultaneously raise the legs and upper body, passing the ball from hands to feet at the top. Lower.'],
            ['name' => 'Medicine Ball Toe Touches', 'equipment' => 'Medicine Ball', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors'], 'description' => 'Lie on back, legs vertical holding the ball between feet, reach up with hands to touch the ball by crunching the abs. Lower and repeat.'],
            ['name' => 'Medicine Ball Plank with Ball Roll', 'equipment' => 'Medicine Ball', 'category_slug' => 'core', 'target_muscles' => ['Transverse Abdominis', 'Rectus Abdominis', 'Obliques', 'Shoulders'], 'description' => 'Assume a plank with forearms on the ball or hands on the ball. Roll the ball forward slightly and back by shifting the body, maintaining plank.'],
            ['name' => 'Medicine Ball Mountain Climbers', 'equipment' => 'Medicine Ball', 'category_slug' => 'cardio', 'target_muscles' => ['Quadriceps', 'Hip Flexors', 'Core', 'Shoulders'], 'description' => 'Place hands on the ball in a plank position, drive knees alternately toward the chest, keeping the ball stable.'],
            ['name' => 'Medicine Ball Lunge with Twist', 'equipment' => 'Medicine Ball', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Obliques', 'Core'], 'description' => 'Hold the ball at chest level, step forward into a lunge, and rotate the torso toward the front leg. Return and alternate.'],
            ['name' => 'Medicine Ball Squat and Press', 'equipment' => 'Medicine Ball', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Shoulders', 'Triceps', 'Core'], 'description' => 'Hold the ball at chest height, squat down, then as you stand, press the ball overhead. Combines lower and upper body.'],
            ['name' => 'Medicine Ball Push-Up on Ball', 'equipment' => 'Medicine Ball', 'category_slug' => 'strength', 'target_muscles' => ['Pectoralis Major', 'Triceps', 'Anterior Deltoids', 'Core'], 'description' => 'Place one or both hands on the ball and perform push-ups. The instability increases core and stabilizer activation.'],
            ['name' => 'Medicine Ball Dead Bug', 'equipment' => 'Medicine Ball', 'category_slug' => 'core', 'target_muscles' => ['Transverse Abdominis', 'Rectus Abdominis', 'Obliques', 'Hip Flexors'], 'description' => 'Lie on back, arms extended holding the ball above chest, legs in tabletop. Slowly extend one leg while keeping the ball still, return and alternate.'],
            ['name' => 'Medicine Ball Hip Thrust (Weighted)', 'equipment' => 'Medicine Ball', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Core'], 'description' => 'Sit on floor, upper back against bench, place the ball across the hips, thrust upward squeezing glutes. The ball adds load.'],
            ['name' => 'Medicine Ball Glute Bridge', 'equipment' => 'Medicine Ball', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings'], 'description' => 'Lie on back, knees bent, place the ball on the hips, drive through heels to lift hips until straight, lower.'],
            ['name' => 'Medicine Ball Hamstring Curl (on Floor)', 'equipment' => 'Medicine Ball', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Core'], 'description' => 'Lie on back, heels on the ball, lift hips, then curl the ball toward you by bending the knees, rolling it, then extend.'],
            ['name' => 'Medicine Ball Good Morning', 'equipment' => 'Medicine Ball', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Erector Spinae', 'Core'], 'description' => 'Hold the ball against your chest or overhead, hinge at the hips with a flat back, lower the torso until hamstring stretch, then return.'],
            ['name' => 'Medicine Ball Overhead Squat', 'equipment' => 'Medicine Ball', 'category_slug' => 'mobility', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Shoulders', 'Core'], 'description' => 'Hold the ball overhead with arms straight, squat as deep as possible while keeping the ball stabilized overhead. Tests shoulder mobility.'],
            ['name' => 'Medicine Ball Goblet Squat', 'equipment' => 'Medicine Ball', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold the ball vertically against your chest with both hands, squat down, keeping the torso upright, then stand.'],
            ['name' => 'Medicine Ball Split Squat', 'equipment' => 'Medicine Ball', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold the ball at your chest, take a staggered stance, lower until back knee nearly touches the floor, then drive up.'],
            ['name' => 'Medicine Ball Curl (Biceps)', 'equipment' => 'Medicine Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps Brachii', 'Brachialis'], 'description' => 'Hold the ball with both hands underhand, curl it up by flexing elbows, squeeze at top, lower with control. The awkward grip challenges forearms.'],
            ['name' => 'Medicine Ball Overhead Triceps Extension', 'equipment' => 'Medicine Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps Brachii (Long Head)'], 'description' => 'Hold the ball with both hands overhead, lower it behind the head by bending elbows, then extend arms straight up.'],
            ['name' => 'Medicine Ball Chest Fly (Floor Press)', 'equipment' => 'Medicine Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids'], 'description' => 'Lie on the floor holding the ball over chest, arms slightly bent, lower it out to the sides in a wide arc, then squeeze it back up.'],
            ['name' => 'Medicine Ball Pullover', 'equipment' => 'Medicine Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Latissimus Dorsi', 'Pectoralis Major', 'Serratus Anterior', 'Triceps'], 'description' => 'Lie across a bench with upper back supported, hold ball overhead with arms straight, pull it over the chest in an arc until it\'s above hips.'],
            ['name' => 'Medicine Ball Lateral Raise', 'equipment' => 'Medicine Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Medial Deltoids', 'Supraspinatus'], 'description' => 'Stand holding the ball in one hand, raise it out to the side until shoulder height, then lower. Can be done with both hands on a ball.'],
            ['name' => 'Medicine Ball Front Raise', 'equipment' => 'Medicine Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Anterior Deltoids'], 'description' => 'Hold the ball with both hands in front of thighs, raise it straight forward to shoulder height, then lower.'],
            ['name' => 'Medicine Ball Bent-Over Row (Single Arm)', 'equipment' => 'Medicine Ball', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Biceps', 'Rear Deltoids'], 'description' => 'Hinge forward, hold the ball with one hand, pull it to the side of the torso, squeeze the back, lower. The round shape challenges grip.'],
            ['name' => 'Medicine Ball Shrug', 'equipment' => 'Medicine Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Upper Trapezius', 'Levator Scapulae'], 'description' => 'Hold the ball with both hands at arm\'s length in front, shrug shoulders upward, squeeze, lower.'],
            ['name' => 'Medicine Ball Calf Raise', 'equipment' => 'Medicine Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Gastrocnemius', 'Soleus'], 'description' => 'Hold the ball at your chest, stand on the balls of your feet on a step, raise your heels as high as possible, then lower.'],
            ['name' => 'Medicine Ball Side Bend', 'equipment' => 'Medicine Ball', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Quadratus Lumborum'], 'description' => 'Stand holding the ball in one hand or overhead, bend laterally at the waist toward the opposite side, then return upright.'],
            ['name' => 'Medicine Ball Reverse Lunge with Rotation', 'equipment' => 'Medicine Ball', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Obliques', 'Core'], 'description' => 'Hold the ball at chest, step back into a reverse lunge while rotating the torso toward the front leg. Return and repeat.'],
            ['name' => 'Medicine Ball Knee Drive (Hang Clean Style)', 'equipment' => 'Medicine Ball', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Shoulders', 'Core'], 'description' => 'Squat holding the ball between legs, explosively extend and catch the ball at chest height while driving knees up. A clean variation.'],
            ['name' => 'Medicine Ball Burpee with Slam', 'equipment' => 'Medicine Ball', 'category_slug' => 'cardio', 'target_muscles' => ['Full Body', 'Quadriceps', 'Glutes', 'Shoulders', 'Core'], 'description' => 'Perform a burpee holding the ball: slam it to the floor, jump feet back, do a push-up on the ball, jump feet forward, pick up ball, and jump to start.'],
            ['name' => 'Medicine Ball Lateral Shuffle Throw', 'equipment' => 'Medicine Ball', 'category_slug' => 'cardio', 'target_muscles' => ['Obliques', 'Quadriceps', 'Glutes', 'Shoulders'], 'description' => 'Shuffle sideways holding the ball, then stop and perform a side throw against a wall, continue shuffling. Combines lateral movement and power.'],
            ['name' => 'Medicine Ball Partner Russian Twist Pass', 'equipment' => 'Medicine Ball', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis'], 'description' => 'Sit back-to-back with a partner, rotate to one side, hand off the ball, then rotate to the other side to receive. Keeps constant tension.'],
            ['name' => 'Medicine Ball Standing Twist (Pallof Press Style)', 'equipment' => 'Medicine Ball', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Transverse Abdominis'], 'description' => 'Stand holding the ball with arms extended forward, rotate the torso to one side, return to center, repeat. Core anti-rotation.'],
            ['name' => 'Medicine Ball Ab Rollout', 'equipment' => 'Medicine Ball', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Transverse Abdominis', 'Obliques', 'Shoulders'], 'description' => 'Kneel with hands on the ball, roll it forward as far as possible while maintaining a straight body, then pull back to start.'],
            ['name' => 'Medicine Ball Superman Hold (Back Extension)', 'equipment' => 'Medicine Ball', 'category_slug' => 'strength', 'target_muscles' => ['Erector Spinae', 'Glutes', 'Rhomboids'], 'description' => 'Lie face down, hold the ball overhead with straight arms, raise the chest and arms off the floor, squeezing the back muscles, hold for time.'],
        ];

        foreach ($exercises as $data) {
            Exercise::create([
                'name' => $data['name'],
                'equipment' => $data['equipment'],
                'category_id' => $categories[$data['category_slug']],
                'target_muscles' => $data['target_muscles'],
                'description' => $data['description'],
            ]);
        }
    }
}
