<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\ExerciseCategory;
use Illuminate\Database\Seeder;

class PlyometricBoxSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ExerciseCategory::pluck('id', 'slug');

        $execises = [
            ['name' => 'Box Jump (Standard)', 'equipment' => 'Plyometric Box', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Calves', 'Core'], 'description' => 'Stand facing the box, squat slightly, then explosively jump up and land softly on top with both feet. Step down and repeat.'],
            ['name' => 'Box Jump (Seated Start)', 'equipment' => 'Plyometric Box', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Calves', 'Core'], 'description' => 'Sit on a lower box or bench, then explode upward onto the taller box without a countermovement. Eliminates the stretch reflex, building pure concentric power.'],
            ['name' => 'Depth Jump (Shock Jump)', 'equipment' => 'Plyometric Box', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Calves', 'Core'], 'description' => 'Stand on top of the box, step off (don\'t jump), land on the ground, and immediately explode vertically or onto another box. Develops reactive strength and amortization phase speed.'],
            ['name' => 'Single-Leg Box Jump', 'equipment' => 'Plyometric Box', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Calves (unilateral)', 'Core'], 'description' => 'Jump onto the box from one leg, landing softly on the same leg or both. Requires significant unilateral power and balance.'],
            ['name' => 'Lateral Box Jump (Side-to-Side)', 'equipment' => 'Plyometric Box', 'category_slug' => 'power', 'target_muscles' => ['Gluteus Medius', 'Quadriceps', 'Glutes', 'Calves', 'Adductors', 'Core'], 'description' => 'Stand beside the box, jump sideways onto it, landing with both feet. Step down and repeat from the other side. Builds lateral power and stability.'],
            ['name' => 'Box Jump with Pause (Stick Landing)', 'equipment' => 'Plyometric Box', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Calves', 'Core'], 'description' => 'Jump onto the box and stick the landing, holding a half-squat position for 2-3 seconds before stepping down. Focuses on control and stability upon landing.'],
            ['name' => 'Continuous Box Jumps (Rebound)', 'equipment' => 'Plyometric Box', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Calves', 'Core'], 'description' => 'Jump onto the box, step or jump down, and immediately rebound back onto the box with no pause. Reduces ground contact time and builds elastic strength.'],
            ['name' => 'Box Step-Up', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Place one foot on the box, drive through the heel to stand on top, then lower back down with control. A foundational strength movement that can be weighted.'],
            ['name' => 'Weighted Box Step-Up', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold dumbbells or a barbell while performing step-ups. Increases resistance for progressive overload.'],
            ['name' => 'Lateral Step-Up', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Gluteus Medius', 'Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Stand sideways to the box, step onto it with the near leg, driving up to stand. Targets the glute medius more than frontal step-ups.'],
            ['name' => 'Box Step-Up with Knee Drive', 'equipment' => 'Plyometric Box', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Hip Flexors', 'Core'], 'description' => 'Step onto the box and drive the opposite knee up toward the chest at the top, balancing momentarily. Adds a dynamic hip flexor component.'],
            ['name' => 'Reverse Lunge off Box (Deficit Lunge)', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Stand on top of the box, step one foot backward off the box into a deep lunge, then drive back up. Increases range of motion.'],
            ['name' => 'Bulgarian Split Squat (Rear Foot Elevated)', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Place the rear foot on the box behind you, squat down with the front leg until the thigh is parallel, then drive back up. Excellent unilateral leg builder.'],
            ['name' => 'Pistol Squat to Box', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Stand on one leg in front of the box, lower yourself into a single-leg squat until you touch the box, then stand back up. The box provides a consistent depth target.'],
            ['name' => 'Elevated Pike Push-Up', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Anterior Deltoids', 'Triceps', 'Upper Pectorals', 'Core'], 'description' => 'Place feet on the box, hands on the floor. Walk hands closer to the feet so the hips are high. Perform push-ups, lowering the head toward the floor. Emphasizes the shoulders.'],
            ['name' => 'Elevated Push-Up (Feet on Box)', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Upper Pectorals', 'Anterior Deltoids', 'Triceps', 'Core'], 'description' => 'Place feet on the box, hands on the floor in a push-up position. Perform push-ups with the decline angle targeting the upper chest.'],
            ['name' => 'Decline Push-Up (Hands on Box)', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Lower Pectorals', 'Anterior Deltoids', 'Triceps', 'Core'], 'description' => 'Place hands on the box, feet on the floor. Perform push-ups to target the lower chest.'],
            ['name' => 'Box Dips', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Triceps', 'Anterior Deltoids', 'Pectorals'], 'description' => 'Sit on the edge of the box, place hands next to hips, fingers forward. Slide off and lower the body by bending the elbows, then press back up.'],
            ['name' => 'Hip Thrust (Shoulders on Box)', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Core'], 'description' => 'Sit on the floor with upper back against the edge of the box, place a barbell or weight across the hips, thrust upward to full extension.'],
            ['name' => 'Glute Bridge (Feet on Box)', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Core'], 'description' => 'Lie on your back with feet on top of the box. Drive through the heels to lift the hips, increasing the range of motion for the glute bridge.'],
            ['name' => 'Box Hamstring Curl (Slider Curl)', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Core'], 'description' => 'Lie on your back, heels on top of the box. Lift the hips, then curl the box toward you by bending the knees, dragging the box (if light) or using it as a fixed point for eccentric loading.'],
            ['name' => 'Incline Plank (Forearms on Box)', 'equipment' => 'Plyometric Box', 'category_slug' => 'core', 'target_muscles' => ['Transverse Abdominis', 'Rectus Abdominis', 'Obliques', 'Shoulders'], 'description' => 'Rest your forearms on the box and extend the legs back into a plank. The incline reduces shoulder load while still targeting the core.'],
            ['name' => 'Decline Plank (Feet on Box)', 'equipment' => 'Plyometric Box', 'category_slug' => 'core', 'target_muscles' => ['Upper Rectus Abdominis', 'Transverse Abdominis', 'Obliques', 'Shoulders'], 'description' => 'Place feet on the box and hands on the floor in a plank. The decline shift more tension to the upper abs and shoulders.'],
            ['name' => 'Box Mountain Climbers', 'equipment' => 'Plyometric Box', 'category_slug' => 'cardio', 'target_muscles' => ['Quadriceps', 'Hip Flexors', 'Core', 'Shoulders'], 'description' => 'Place hands on the box in a plank position. Drive the knees alternately toward the chest rapidly. The elevated angle reduces wrist strain.'],
            ['name' => 'Box Sprinters (Foot Taps)', 'equipment' => 'Plyometric Box', 'category_slug' => 'cardio', 'target_muscles' => ['Quadriceps', 'Hip Flexors', 'Calves', 'Core'], 'description' => 'Stand facing the box, quickly alternate tapping the top of the box with each foot, mimicking sprinting motion. High intensity cardio and hip flexor work.'],
            ['name' => 'Lateral Box Shuffle (Side-to-Side Taps)', 'equipment' => 'Plyometric Box', 'category_slug' => 'cardio', 'target_muscles' => ['Quadriceps', 'Glutes', 'Adductors', 'Abductors', 'Calves', 'Core'], 'description' => 'Stand beside the box, tap one foot on top, then quickly shuffle to the other side and tap with the other foot. Lateral speed and agility.'],
            ['name' => 'Box Jump Over (Lateral)', 'equipment' => 'Plyometric Box', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Calves', 'Obliques', 'Core'], 'description' => 'Start on one side of the box, jump laterally over it (not onto it), landing on the opposite side, and immediately jump back. Rapid lateral power.'],
            ['name' => 'Burpee Box Jump', 'equipment' => 'Plyometric Box', 'category_slug' => 'cardio', 'target_muscles' => ['Full Body', 'Quadriceps', 'Glutes', 'Shoulders', 'Core'], 'description' => 'Perform a burpee in front of the box, then at the top, jump onto the box instead of straight up. Step down and repeat.'],
            ['name' => 'Box Jump to Depth Jump (Plyo Combo)', 'equipment' => 'Plyometric Box', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Calves', 'Core'], 'description' => 'Jump onto a lower box, step off, land and immediately explode into a higher box jump. Chains multiple plyometric movements.'],
            ['name' => 'Single-Leg Depth Jump', 'equipment' => 'Plyometric Box', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Calves (unilateral)', 'Core'], 'description' => 'Step off the box with one leg, land on one leg and immediately explode upward or forward. Very high intensity unilateral plyometric.'],
            ['name' => 'Box Calf Raise (Standing)', 'equipment' => 'Plyometric Box', 'category_slug' => 'isolation', 'target_muscles' => ['Gastrocnemius', 'Soleus'], 'description' => 'Stand with the balls of your feet on the edge of the box, heels hanging off. Raise the heels as high as possible, then lower for a deep stretch.'],
            ['name' => 'Seated Calf Raise (on Box)', 'equipment' => 'Plyometric Box', 'category_slug' => 'isolation', 'target_muscles' => ['Soleus', 'Gastrocnemius'], 'description' => 'Sit on a bench with feet on the edge of the box, place weight on the knees, and raise the heels.'],
            ['name' => 'Elevated Back Extension (on Box)', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Erector Spinae', 'Glutes', 'Hamstrings'], 'description' => 'Lie face down with hips on the edge of the box, feet anchored under something or held by a partner. Extend the spine to raise the torso, then lower.'],
            ['name' => 'Box Hamstring Walkout (Glute-Ham Negative)', 'equipment' => 'Plyometric Box', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Core'], 'description' => 'Kneel on the box with feet secured, lower the torso forward slowly using the hamstrings to resist gravity, then catch yourself with hands and push back up.'],
        ];

        foreach ($execises as $data) {
            Exercise::create([
                'name' => $data['name'],
                'equipment' => $data['equipment'],
                'category_id' => $categories[$data['category_slug']],
                'target_muscles' => $data['target_muscles'],
                'description' => $data['description'],
            ]);
        }
    }
}
