<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\ExerciseCategory;
use Illuminate\Database\Seeder;

class PullUpBarSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ExerciseCategory::pluck('id', 'slug');

        $exercises = [
            ['name' => 'Standard Pull-Up (Overhand Wide Grip)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Middle Traps', 'Biceps', 'Rear Deltoids', 'Core'], 'description' => 'Grip the bar with an overhand grip wider than shoulder-width. Hang freely, then pull yourself up until the chin clears the bar. Lower with control to a dead hang.'],
            ['name' => 'Chin-Up (Underhand Shoulder-Width Grip)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Brachialis', 'Rhomboids', 'Core'], 'description' => 'Grip the bar with an underhand (supinated) grip, hands shoulder-width apart. Pull up until the chin is over the bar. Greater biceps involvement than standard pull-ups.'],
            ['name' => 'Neutral Grip Pull-Up (Parallel Grip)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Brachialis', 'Middle Traps', 'Core'], 'description' => 'Use parallel handles if available (palms facing each other). Pull up until chin clears the handles. Easier on the wrists and shifts emphasis to the brachialis.'],
            ['name' => 'Close-Grip Pull-Up (Overhand Narrow Grip)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi (lower)', 'Biceps', 'Brachialis', 'Middle Back'], 'description' => 'Grip the bar with an overhand grip, hands close together. Pull up to the lower chest, keeping elbows close. Emphasizes lower lats and biceps.'],
            ['name' => 'Close-Grip Chin-Up (Underhand Narrow Grip)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Brachialis'], 'description' => 'Use an underhand grip with hands very close together. Pull up high, focusing on bicep contraction. Intense arm and lat engagement.'],
            ['name' => 'Commando Pull-Up (Side-to-Side)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Obliques', 'Core'], 'description' => 'Stand sideways under the bar, grip it with one hand in front of the face and one behind the head. Pull up so the head moves to one side, alternating sides each rep.'],
            ['name' => 'Archer Pull-Up', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi (unilateral)', 'Biceps', 'Core'], 'description' => 'Pull up toward one hand while the other arm straightens horizontally. Switch sides each rep. Advanced unilateral pulling strength.'],
            ['name' => 'Typewriter Pull-Up', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Obliques', 'Core'], 'description' => 'Pull up to the top, then shift the body side to side horizontally along the bar, keeping the chin above the bar. Intense lat and core control.'],
            ['name' => 'Weighted Pull-Up', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Rhomboids', 'Core'], 'description' => 'Attach weight via a dip belt, weighted vest, or hold a dumbbell between the feet. Perform a standard pull-up with added resistance for progressive overload.'],
            ['name' => 'Negative (Eccentric) Pull-Up', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Rhomboids'], 'description' => 'Use a box or jump to start at the top of the bar (chin over). Lower yourself as slowly as possible (4-5 seconds) until the arms are fully extended. Builds pulling strength for full pull-ups.'],
            ['name' => 'Pause Pull-Up', 'equipment' => 'Pull-up Bar', 'category_slug' => 'hypertrophy', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Rhomboids'], 'description' => 'Pull up until the chin clears the bar, hold the top position for 1-3 seconds squeezing the back, then lower. Eliminates momentum and increases time under tension.'],
            ['name' => 'Tempo Pull-Up (3-1-3)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'hypertrophy', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Core'], 'description' => 'Take 3 seconds to pull up, hold at the top for 1 second, then take 3 seconds to lower. Maximizes muscular control and time under tension.'],
            ['name' => 'Explosive Pull-Up (Speed Pull-Up)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'power', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Core'], 'description' => 'Pull up as fast and explosively as possible, allowing the hands to leave the bar slightly at the top (clapping pull-up) or just driving up with maximum intent. Builds power.'],
            ['name' => 'Kipping Pull-Up', 'equipment' => 'Pull-up Bar', 'category_slug' => 'power', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Core', 'Hip Flexors', 'Glutes'], 'description' => 'Use a rhythmic swing of the body (hip drive) to generate momentum to assist the pull-up. Used in CrossFit for high-rep efficiency.'],
            ['name' => 'Butterfly Pull-Up', 'equipment' => 'Pull-up Bar', 'category_slug' => 'power', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Core', 'Hip Flexors', 'Glutes'], 'description' => 'A continuous, fluid kipping pull-up variation where the legs cycle in a circular motion, minimizing pause and maximizing speed.'],
            ['name' => 'Chest-to-Bar Pull-Up', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Biceps', 'Core'], 'description' => 'Pull up until the chest (not just the chin) touches the bar. Requires greater pulling range and strength than standard pull-ups.'],
            ['name' => 'Sternum Pull-Up', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Traps', 'Biceps', 'Rear Deltoids'], 'description' => 'Lean the torso back, pull until the sternum or lower chest touches the bar. Changes the angle to hit the lats and middle back more heavily.'],
            ['name' => 'Mixed Grip Pull-Up (One Over, One Under)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Brachioradialis', 'Core'], 'description' => 'One hand overhand, one hand underhand. Pull up evenly; the underhand side works biceps more, overhand works lats more. Alternate between sets to balance.'],
            ['name' => 'Towel Pull-Up', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Forearms', 'Grip'], 'description' => 'Drape a towel or two over the bar, grip the towel ends, and perform pull-ups. Severely challenges grip and forearm strength.'],
            ['name' => 'L-Sit Pull-Up', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Rectus Abdominis', 'Hip Flexors', 'Core'], 'description' => 'Hold the legs straight out in front (forming an L-shape) while performing pull-ups. Increases core engagement and removes leg drive.'],
            ['name' => 'Behind-the-Neck Pull-Up', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Rear Deltoids', 'Middle Traps'], 'description' => 'Pull up and lower the bar behind the neck. Requires good shoulder mobility. Hits the upper back and rear delts differently.'],
            ['name' => 'Band-Assisted Pull-Up', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Core'], 'description' => 'Loop a resistance band over the bar, place one foot or knee in the band. The band assists the concentric phase, allowing full reps to build volume.'],
            ['name' => 'Hanging Scapular Retraction (Scap Pull-Up)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'strength', 'target_muscles' => ['Rhomboids', 'Lower Traps', 'Latissimus Dorsi'], 'description' => 'Hang from the bar with straight arms. Pull the shoulder blades down and together without bending the elbows. Builds foundational back strength and shoulder stability.'],
            ['name' => 'Active Hang', 'equipment' => 'Pull-up Bar', 'category_slug' => 'mobility', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Grip', 'Shoulders'], 'description' => 'Hang from the bar keeping the shoulders engaged (pulled down) and the core tight. Holds for time to build grip and shoulder girdle endurance.'],
            ['name' => 'Dead Hang', 'equipment' => 'Pull-up Bar', 'category_slug' => 'mobility', 'target_muscles' => ['Forearms', 'Grip', 'Shoulders', 'Spine'], 'description' => 'Hang completely relaxed, letting the shoulders elevate and the spine decompress. Improves grip strength and shoulder mobility.'],
            ['name' => 'Hanging Knee Raise', 'equipment' => 'Pull-up Bar', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Obliques'], 'description' => 'Hang from the bar with straight arms, bring the knees up toward the chest by curling the pelvis. Lower with control.'],
            ['name' => 'Hanging Leg Raise (Straight Leg)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Transverse Abdominis'], 'description' => 'Hang with legs straight. Raise the legs in front of you until they are parallel to the floor or higher, then lower without swinging.'],
            ['name' => 'Hanging Toes-to-Bar', 'equipment' => 'Pull-up Bar', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Obliques', 'Grip'], 'description' => 'Hang and swing the legs up until the toes touch the bar. Requires dynamic core power and strong grip. Can be strict or with a slight swing.'],
            ['name' => 'Hanging L-Sit Hold', 'equipment' => 'Pull-up Bar', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Obliques', 'Transverse Abdominis', 'Quadriceps'], 'description' => 'Hold yourself on the bar with straight arms, legs held straight out at a 90° angle. Maintain the position for time. Intense static core and hip flexor strength.'],
            ['name' => 'Hanging Windshield Wiper', 'equipment' => 'Pull-up Bar', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis', 'Hip Abductors'], 'description' => 'Hang from the bar, raise the legs to an L-sit or toes-to-bar, then rotate the legs side to side in a controlled arc. Oblique and grip strength challenge.'],
            ['name' => 'Hanging Oblique Knee Raise', 'equipment' => 'Pull-up Bar', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Hip Flexors'], 'description' => 'Hang and bring the knees up diagonally toward one armpit, then the other, alternating. Targets the obliques dynamically.'],
            ['name' => 'Hanging Figure-Eight (Knees or Legs)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Obliques', 'Hip Flexors'], 'description' => 'Trace a figure-eight pattern with the legs while hanging. Deep core control and coordination.'],
            ['name' => 'Around-the-World Pull-Up Bar Hang (Swing Rotation)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'mobility', 'target_muscles' => ['Shoulders', 'Core', 'Grip'], 'description' => 'Hang and swing the legs in a wide circle, rotating the torso and shoulders. Dynamic mobility and shoulder girdle warm-up.'],
            ['name' => 'Muscle-Up (Bar)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'power', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Triceps', 'Pectorals', 'Core', 'Shoulders'], 'description' => 'Perform an explosive pull-up transitioning into a dip over the bar. Combines a vertical pull with a push. Advanced bodyweight power movement.'],
            ['name' => 'Pull-Up Bar Rollover (Skin the Cat)', 'equipment' => 'Pull-up Bar', 'category_slug' => 'mobility', 'target_muscles' => ['Shoulders', 'Rotator Cuff', 'Core', 'Grip'], 'description' => 'Hang, tuck the knees up and roll backward over the bar until the body is inverted, then reverse. Improves shoulder mobility and control.'],
        ];

        foreach ($exercises as $data) {
            Exercise::create([
                'name' => $data['name'],
                'equipment' => $data['equipment'],
                'category_id' => $categories[$data['category_slug']],
                'target_muscles' => $data['target_muscles'],
                'description' => $data['description'],
            ]);
        }
    }
}
