<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\ExerciseCategory;
use Illuminate\Database\Seeder;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Storage;

class ResistanceBandSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ExerciseCategory::pluck('id', 'slug');

        $execises = [
            ['name' => 'Band Pull-Apart', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Rear Deltoids', 'Rhomboids', 'Middle Traps', 'Rotator Cuff'], 'description' => 'Hold the band with both hands in front of the chest at shoulder height. Keeping the arms straight, pull the band apart by squeezing the shoulder blades until the arms are extended out to the sides.'],
            ['name' => 'Band Overhead Pull-Apart', 'equipment' => 'Resistance Band', 'category_slug' => 'mobility', 'target_muscles' => ['Rear Deltoids', 'Rhomboids', 'Shoulders'], 'description' => 'Hold the band overhead with straight arms. Pull it apart and bring it down behind the head while keeping the arms straight, then return. Improves shoulder mobility and posture.'],
            ['name' => 'Band Face Pull', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Rear Deltoids', 'Rhomboids', 'External Rotators'], 'description' => 'Anchor the band at head height or hold it with both hands. Pull the band toward the face, separating the hands and externally rotating the shoulders. Squeeze the upper back.'],
            ['name' => 'Band Bent-Over Row', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Biceps', 'Rear Deltoids'], 'description' => 'Stand on the band with feet hip-width apart, hinge forward. Hold the band ends and row them to the sides of the torso, squeezing the shoulder blades.'],
            ['name' => 'Band Seated Row', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Biceps'], 'description' => 'Sit on the floor with legs extended, loop the band around the feet. Hold the ends and pull the band toward the lower abdomen, squeezing the back.'],
            ['name' => 'Band Single-Arm Row', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi (unilateral)', 'Rhomboids', 'Biceps'], 'description' => 'Anchor the band low or stand on one end. Hinge forward, row the band to the hip with one arm. Unilateral back strength.'],
            ['name' => 'Band Lat Pulldown', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Biceps', 'Rhomboids'], 'description' => 'Secure the band overhead (door anchor or bar). Kneel or sit and pull the band down to the chest, keeping the chest up, squeezing the lats.'],
            ['name' => 'Band Straight-Arm Pulldown', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Latissimus Dorsi', 'Triceps Long Head'], 'description' => 'Anchor the band overhead. With straight arms, pull the band down in an arc toward the thighs, squeezing the lats. Isolates the back without biceps.'],
            ['name' => 'Band Push-Up (Band Across Back)', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'], 'description' => 'Loop a band across the back and hold the ends under the hands. Perform push-ups against the added band resistance. Increases chest and tricep load at the top.'],
            ['name' => 'Band Chest Press', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids', 'Triceps'], 'description' => 'Anchor the band behind you at chest height. Hold the ends, step forward, and press the hands straight out in front until the arms are extended. The band simulates a cable or machine press.'],
            ['name' => 'Band Chest Fly', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids'], 'description' => 'Anchor the band behind you at chest height. Hold the ends with arms extended to the sides, slight bend in elbows. Bring the hands together in front in a hugging motion.'],
            ['name' => 'Band Overhead Press', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps'], 'description' => 'Stand on the band with feet shoulder-width. Hold the ends at shoulder height and press overhead, extending the arms fully. The resistance increases at the top.'],
            ['name' => 'Band Lateral Raise', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Medial Deltoids', 'Supraspinatus'], 'description' => 'Stand on the band with one or both feet. Hold the ends at the sides and raise the arms laterally to shoulder height. Band tension increases through the hardest part of the movement.'],
            ['name' => 'Band Front Raise', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Anterior Deltoids'], 'description' => 'Stand on the band, hold the ends in front of the thighs. Raise the arms straight forward to shoulder height. Constant tension on the front delts.'],
            ['name' => 'Band Upright Row', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Medial Deltoids', 'Upper Traps', 'Biceps'], 'description' => 'Stand on the band with feet together. Hold the band with both hands, pull it up along the body to chin height, leading with the elbows.'],
            ['name' => 'Band Shrug', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Upper Trapezius', 'Levator Scapulae'], 'description' => 'Stand on the band, hold the ends with arms straight at the sides. Shrug the shoulders up toward the ears, squeeze, and lower.'],
            ['name' => 'Band Biceps Curl', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps Brachii', 'Brachialis'], 'description' => 'Stand on the band with feet shoulder-width, hold the ends with palms up. Curl the hands to the shoulders by flexing the elbows, then lower with control. Constant tension throughout.'],
            ['name' => 'Band Hammer Curl', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps', 'Brachialis', 'Brachioradialis'], 'description' => 'Stand on the band, hold the ends with a neutral grip (palms facing each other). Curl the hands up, keeping the wrists straight.'],
            ['name' => 'Band Reverse Curl', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Brachioradialis', 'Wrist Extensors', 'Biceps'], 'description' => 'Stand on the band, grip with palms down. Curl the hands upward, keeping the elbows stationary. Focuses on the forearms and brachioradialis.'],
            ['name' => 'Band Triceps Pushdown', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps Brachii'], 'description' => 'Anchor the band overhead (door or hook). Hold the ends with elbows bent at 90°, press the hands down until the arms are straight, squeezing the triceps.'],
            ['name' => 'Band Overhead Triceps Extension', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps Brachii (Long Head)'], 'description' => 'Stand on one end of the band or anchor it low. Hold the other end behind the head, elbow pointed up. Extend the arm overhead. Hits the long head of the triceps.'],
            ['name' => 'Band Triceps Kickback', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps Brachii (Lateral Head)'], 'description' => 'Stand on the band, hinge forward. Hold the ends with the upper arms parallel to the body. Extend the arms straight back, squeezing the triceps.'],
            ['name' => 'Band Squat (Shoulder Racked)', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Stand on the band with feet shoulder-width, hold the ends at the shoulders. Squat down keeping the torso upright, then drive back up. The band adds resistance progressively.'],
            ['name' => 'Band Goblet Squat', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Anchor the band under the feet, hold the other end with both hands at the chest. Squat down, then stand. The band pull increases core engagement.'],
            ['name' => 'Band Overhead Squat', 'equipment' => 'Resistance Band', 'category_slug' => 'mobility', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Shoulders', 'Core'], 'description' => 'Hold the band with wide arms overhead, stand on it or not. Squat while keeping the band pulled taut and overhead. Challenges shoulder mobility and core stability.'],
            ['name' => 'Band Split Squat', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Stand on the band with the front foot in a staggered stance. Hold the ends at shoulders. Lower into a lunge and press up. Band adds resistance to unilateral leg work.'],
            ['name' => 'Band Deadlift', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Erector Spinae'], 'description' => 'Stand on the band with feet hip-width. Hold the ends (or a bar with bands attached). Hinge at the hips and stand up, squeezing the glutes. Reinforces hip hinge mechanics.'],
            ['name' => 'Band Romanian Deadlift', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Erector Spinae'], 'description' => 'Stand on the band, hinge forward with a slight knee bend, pushing the hips back. Feel the hamstring stretch, then return by extending the hips.'],
            ['name' => 'Band Single-Leg Deadlift', 'equipment' => 'Resistance Band', 'category_slug' => 'stability', 'target_muscles' => ['Hamstrings', 'Glutes', 'Core', 'Balance'], 'description' => 'Stand on one leg with the band under that foot. Hinge forward, holding the band with one or both hands. Return to standing. Unilateral posterior chain and balance.'],
            ['name' => 'Band Glute Bridge', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings'], 'description' => 'Lie on your back, knees bent, band across the hips anchored by the hands or wrapped around the hips. Drive through the heels to lift the hips. The band adds resistance.'],
            ['name' => 'Band Hip Thrust', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Core'], 'description' => 'Sit with upper back against a bench, band across the hips, anchored under the feet or held. Thrust upward to full hip extension.'],
            ['name' => 'Band Hamstring Curl (Prone)', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Hamstrings'], 'description' => 'Anchor the band low. Lie face down, loop the band around one ankle. Curl the heel toward the glutes, keeping the hips on the floor.'],
            ['name' => 'Band Standing Leg Curl', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Hamstrings'], 'description' => 'Anchor the band low, loop it around one ankle. Stand facing the anchor and curl the heel toward the glute. Isolates the hamstring.'],
            ['name' => 'Band Leg Extension (Seated)', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Quadriceps'], 'description' => 'Sit on a chair, anchor the band to the chair leg and loop around the ankle. Extend the leg straight out in front, squeezing the quad.'],
            ['name' => 'Band Hip Abduction (Standing)', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Gluteus Medius', 'Gluteus Minimus'], 'description' => 'Anchor the band low, loop it around the far ankle. Stand sideways and lift the leg out to the side against the band. Also can be done with a mini band around the ankles.'],
            ['name' => 'Band Hip Adduction (Standing)', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Adductors'], 'description' => 'Anchor the band low, loop it around the near ankle. Stand sideways to the anchor and cross the leg in front of the body toward the midline.'],
            ['name' => 'Band Donkey Kick', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Gluteus Maximus', 'Hamstrings'], 'description' => 'On all fours, place the band around one foot and hold the other end with the hands. Kick the foot straight back, extending the hip.'],
            ['name' => 'Band Fire Hydrant', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Gluteus Medius', 'Gluteus Minimus'], 'description' => 'On all fours, band around thighs or looped from foot to hands. Lift one knee out to the side, keeping the hip bent at 90°.'],
            ['name' => 'Band Calf Raise (Standing)', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Gastrocnemius', 'Soleus'], 'description' => 'Stand on the band, hold the ends at the shoulders or sides. Raise the heels off the floor as high as possible, then lower.'],
            ['name' => 'Band Seated Calf Raise', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Soleus', 'Gastrocnemius'], 'description' => 'Sit on a chair, loop the band over the knees, place the balls of the feet on a block. Raise the heels, pressing against the band.'],
            ['name' => 'Band Woodchop (High-to-Low)', 'equipment' => 'Resistance Band', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Transverse Abdominis', 'Rectus Abdominis'], 'description' => 'Anchor the band overhead. Stand sideways, hold the band with both hands, and chop diagonally down across the body, rotating the torso.'],
            ['name' => 'Band Woodchop (Low-to-High)', 'equipment' => 'Resistance Band', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Transverse Abdominis', 'Rectus Abdominis'], 'description' => 'Anchor the band low. Stand sideways, hold the band, and pull it diagonally upward across the body, rotating the core.'],
            ['name' => 'Band Pallof Press (Anti-Rotation)', 'equipment' => 'Resistance Band', 'category_slug' => 'core', 'target_muscles' => ['Transverse Abdominis', 'Obliques', 'Rectus Abdominis'], 'description' => 'Anchor the band at chest height. Stand sideways, hold the band with both hands at the sternum. Press the arms straight out, resisting the rotational pull, then return.'],
            ['name' => 'Band Russian Twist', 'equipment' => 'Resistance Band', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis'], 'description' => 'Sit on the floor, anchor the band low to one side. Hold the band with both hands, lean back, and rotate the torso away from the anchor against resistance.'],
            ['name' => 'Band Crunch (Seated or Kneeling)', 'equipment' => 'Resistance Band', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis'], 'description' => 'Anchor the band overhead. Kneel or sit holding the band behind the head. Crunch forward, curling the torso against the band resistance.'],
            ['name' => 'Band Side Bend', 'equipment' => 'Resistance Band', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Quadratus Lumborum'], 'description' => 'Stand on one end of the band, hold the other end with one hand. Bend laterally at the waist against the band resistance, then return.'],
            ['name' => 'Band Good Morning', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Erector Spinae', 'Core'], 'description' => 'Stand on the band with feet shoulder-width, drape the band over the upper back holding the ends in front of the shoulders. Hinge forward at the hips, then stand up.'],
            ['name' => 'Band Pull-Through', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Erector Spinae'], 'description' => 'Anchor the band low behind you. Face away, hold the band between the legs, hinge at the hips, then drive the hips forward explosively to stand.'],
            ['name' => 'Band Sprint (Resisted Running)', 'equipment' => 'Resistance Band', 'category_slug' => 'cardio', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Calves', 'Core'], 'description' => 'Have a partner hold the band around your waist or anchor it securely. Sprint in place or forward against the band\'s resistance.'],
            ['name' => 'Band Lateral Walk (Side Steps)', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Gluteus Medius', 'Gluteus Minimus', 'Quadriceps'], 'description' => 'Place a mini loop band around the ankles or lower thighs. Assume a half-squat position and step sideways, maintaining tension on the band. Switch directions.'],
            ['name' => 'Band Monster Walk', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Gluteus Medius', 'Gluteus Maximus'], 'description' => 'Loop band around ankles or above knees. Walk forward at a 45-degree angle, then backward, keeping feet wide and tension constant.'],
            ['name' => 'Band Clamshell', 'equipment' => 'Resistance Band', 'category_slug' => 'isolation', 'target_muscles' => ['Gluteus Medius', 'Gluteus Minimus'], 'description' => 'Lie on your side with the loop band above the knees. Keep the feet together and open the top knee against the band\'s resistance, then close.'],
            ['name' => 'Band Glute Bridge with Abduction (Banded Bridge)', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Gluteus Maximus', 'Gluteus Medius', 'Hamstrings'], 'description' => 'Place the loop band above the knees. Perform a glute bridge. At the top, push the knees outward against the band, squeezing the glutes.'],
            ['name' => 'Band-Resisted Push-Up (Band on Wrists)', 'equipment' => 'Resistance Band', 'category_slug' => 'strength', 'target_muscles' => ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'], 'description' => 'Loop a band around the back and hold the ends under the palms. Perform push-ups. The band increases resistance at the top.'],
        ];

        $sourceDir = public_path('execises/resistance-band');
        $files = glob($sourceDir . '/*.png');
        sort($files);

        foreach ($execises as $i => $data) {
            $sourceFile = $files[$i] ?? null;

            if ($sourceFile) {
                $data['image'] = Storage::disk('public')->putFile('exercises', new File($sourceFile));
            }

            Exercise::create([
                'name' => $data['name'],
                'equipment' => $data['equipment'],
                'category_id' => $categories[$data['category_slug']],
                'target_muscles' => $data['target_muscles'],
                'description' => $data['description'],
                'image' => $data['image'] ?? null,
            ]);
        }
    }
}
