<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\ExerciseCategory;
use Illuminate\Database\Seeder;

class SandbagSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ExerciseCategory::pluck('id', 'slug');

        $execises = [
            ['name' => 'Bear Hug Squat', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core', 'Biceps'], 'description' => 'Hug the sandbag tightly against your chest with both arms. Squat down until thighs are at least parallel, keeping the chest up, then drive back to standing. The shifting weight challenges core stability.'],
            ['name' => 'Zercher Squat', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core', 'Biceps'], 'description' => 'Cradle the sandbag in the crooks of your elbows, hold it high against your chest. Squat while maintaining an upright torso. The forward load heavily engages the upper back and core.'],
            ['name' => 'Overhead Squat', 'equipment' => 'Sandbag', 'category_slug' => 'mobility', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Shoulders', 'Core'], 'description' => 'Press the sandbag overhead with arms locked, hands grasping the bag. Squat as deep as possible while keeping the bag stable overhead. Demands extreme shoulder mobility and core control.'],
            ['name' => 'Front Squat (Cross-Arm)', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Core', 'Upper Back'], 'description' => 'Hold the sandbag on the front of the shoulders, arms crossed over it. Squat down with an upright torso. The unstable bag forces constant core tension.'],
            ['name' => 'Split Squat', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold the sandbag in a bear hug or on the back. Take a staggered stance, lower until the back knee nearly touches the floor, then drive up. Unilateral leg strength and stability.'],
            ['name' => 'Bulgarian Split Squat', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Elevate the rear foot on a bench, hold the sandbag at the chest, and squat down with the front leg. The unstable load increases the balance challenge.'],
            ['name' => 'Walking Lunge', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold the sandbag across the chest or on the shoulders. Step forward into a lunge, lower the rear knee, then push up and step into the next lunge. Continuous walking challenges coordination.'],
            ['name' => 'Reverse Lunge', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold the sandbag at your chest, step backward into a lunge, lower until both knees are 90°, then return to start. Unilateral leg work with a shifting load.'],
            ['name' => 'Lateral Lunge', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Adductors', 'Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold the sandbag at the chest. Step out to the side, sit back into the hip of the bent leg, keep the other leg straight. Push back to start. Engages inner thighs.'],
            ['name' => 'Step-Up', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold the sandbag in a bear hug. Step onto a box or bench with one foot, drive through the heel to stand, then lower back down. The shifting sand makes each rep unique.'],
            ['name' => 'Sandbag Deadlift', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Erector Spinae', 'Quadriceps', 'Traps', 'Grip'], 'description' => 'Stand with the sandbag between your feet. Squat, grab the bag by its sides or ends, keep the back flat, and lift by extending hips and knees. The shifting mass challenges grip and core.'],
            ['name' => 'Sumo Deadlift', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Adductors', 'Hamstrings', 'Quadriceps', 'Erector Spinae'], 'description' => 'Take a wide stance with toes out. Grip the sandbag with a narrow grip between the legs. Pull the bag up by driving the knees out and hips forward. Emphasises inner thighs.'],
            ['name' => 'Romanian Deadlift', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Erector Spinae'], 'description' => 'Hold the sandbag at hip level with both hands. Hinge at the hips with a slight knee bend, lower the bag along the legs until a deep hamstring stretch, then return by extending the hips.'],
            ['name' => 'Single-Leg Deadlift', 'equipment' => 'Sandbag', 'category_slug' => 'stability', 'target_muscles' => ['Hamstrings', 'Glutes', 'Core', 'Balance'], 'description' => 'Hold the sandbag in both hands or cradled. Stand on one leg, hinge forward while extending the free leg behind you. Return to standing. The shifting load intensifies the balance challenge.'],
            ['name' => 'Clean to Shoulder (Ground)', 'equipment' => 'Sandbag', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Erector Spinae', 'Traps', 'Biceps', 'Core'], 'description' => 'Start with the sandbag on the floor. Explosively pull it up, catching it on one shoulder or across both shoulders. Drive through the hips and use momentum. The shifting sand forces full-body coordination.'],
            ['name' => 'Hang Clean', 'equipment' => 'Sandbag', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Traps', 'Shoulders', 'Core'], 'description' => 'Hold the sandbag at hip level, dip slightly, then explosively extend and pull the bag onto the shoulders. Emphasises the second pull of the clean.'],
            ['name' => 'Over-the-Shoulder Toss', 'equipment' => 'Sandbag', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Erector Spinae', 'Traps', 'Core'], 'description' => 'Squat with the sandbag between legs, then explode upward and toss the bag over one shoulder behind you. Turn, repeat. Builds explosive posterior chain power.'],
            ['name' => 'Shouldering (Alternating)', 'equipment' => 'Sandbag', 'category_slug' => 'power', 'target_muscles' => ['Glutes', 'Hamstrings', 'Quadriceps', 'Obliques', 'Core', 'Shoulders'], 'description' => 'Lift the sandbag from the floor and rest it on one shoulder. Lower it back down, then lift to the other shoulder. The twisting motion and heavy load build rotational strength.'],
            ['name' => 'Push Press', 'equipment' => 'Sandbag', 'category_slug' => 'power', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Quadriceps', 'Core'], 'description' => 'Hold the sandbag at chest height. Dip slightly at the knees, then explosively drive upward and press the bag overhead. Leg drive assists the press. The shifting weight tests stability.'],
            ['name' => 'Strict Press (Overhead)', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Core'], 'description' => 'Stand holding the sandbag at shoulder level with both hands. Press it overhead without leg drive, locking the arms. The unstable load forces the shoulders and core to stabilise.'],
            ['name' => 'Thruster', 'equipment' => 'Sandbag', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Shoulders', 'Triceps', 'Core'], 'description' => 'Hold the sandbag at the chest in a bear hug. Squat down, then as you rise, explosively press the bag overhead in one fluid motion. A full-body combination.'],
            ['name' => 'Bent-Over Row (Bear Hug Row)', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Traps', 'Biceps', 'Erector Spinae'], 'description' => 'Hinge forward with a flat back, holding the sandbag with both arms straight down. Row the bag to the lower abdomen, squeezing the shoulder blades. The shifting weight challenges grip and back.'],
            ['name' => 'Single-Arm Bent-Over Row', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi (unilateral)', 'Rhomboids', 'Biceps', 'Core'], 'description' => 'Hold the sandbag by one end while in a hinged position, support yourself with the other hand on a bench or knee. Row the bag to your hip. Unilateral back strength with anti-rotation.'],
            ['name' => 'Floor Press', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids', 'Triceps'], 'description' => 'Lie on the floor, hold the sandbag above your chest with both hands. Press it straight up to lockout, then lower. The bag\'s shape and shifting weight increase stabiliser demand.'],
            ['name' => 'Pullover', 'equipment' => 'Sandbag', 'category_slug' => 'isolation', 'target_muscles' => ['Latissimus Dorsi', 'Pectoralis Major', 'Serratus Anterior', 'Triceps Long Head'], 'description' => 'Lie across a bench with upper back supported, hold the sandbag overhead with both hands. Pull it over the chest in an arc until above the hips. Stretches the lats and chest.'],
            ['name' => 'Overhead Triceps Extension', 'equipment' => 'Sandbag', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps Brachii (Long Head)'], 'description' => 'Stand or sit holding the sandbag overhead with both hands. Lower it behind the head by bending the elbows, then extend the arms to lockout. The shifting sand demands constant tricep tension.'],
            ['name' => 'Biceps Curl (Bear Hug Curl)', 'equipment' => 'Sandbag', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps Brachii', 'Brachialis'], 'description' => 'Hold the sandbag with an underhand grip or bear hug at waist level. Curl it up by flexing the elbows, squeezing at the top. The unstable load forces the forearms to work harder.'],
            ['name' => 'Hammer Curl (Neutral Grip)', 'equipment' => 'Sandbag', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps', 'Brachialis', 'Brachioradialis'], 'description' => 'Hold the sandbag by its sides with palms facing each other. Curl the bag up, keeping the wrists neutral. Thick grip demands more brachialis recruitment.'],
            ['name' => 'Upright Row', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Medial Deltoids', 'Upper Traps', 'Biceps'], 'description' => 'Hold the sandbag with both hands in front of thighs, grip the sides. Pull it up along the body to chin height, leading with the elbows. The bag\'s bulk challenges shoulder width.'],
            ['name' => 'Shrug', 'equipment' => 'Sandbag', 'category_slug' => 'isolation', 'target_muscles' => ['Upper Trapezius', 'Levator Scapulae'], 'description' => 'Hold the sandbag at arm\'s length in front of you. Shrug your shoulders straight up toward your ears, squeeze, and lower. The weight pulls your shoulders into deep protraction.'],
            ['name' => 'Good Morning', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Erector Spinae', 'Core'], 'description' => 'Place the sandbag across the upper back, holding it in place. Hinge forward at the hips with a flat back until a stretch in the hamstrings, then return to standing. The shifting load increases spinal erector demand.'],
            ['name' => 'Hip Thrust', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Core'], 'description' => 'Sit on the floor, upper back against a bench, sandbag across the hips. Drive through the heels to extend the hips upward, squeezing the glutes at the top. The sandbag molds to the body.'],
            ['name' => 'Glute Bridge', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings'], 'description' => 'Lie on your back, knees bent, sandbag across the hips. Push through the feet to lift the hips until the body forms a straight line from shoulders to knees. Lower under control.'],
            ['name' => 'Hamstring Curl (Floor Slide)', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Core'], 'description' => 'Lie on your back, heels on the sandbag, lift the hips, then curl the bag toward you by bending the knees, sliding it along the floor. Extend back. Constant tension on the hamstrings.'],
            ['name' => 'Russian Twist', 'equipment' => 'Sandbag', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis'], 'description' => 'Sit with knees bent, lean back slightly, hold the sandbag with both hands. Rotate the torso side to side, tapping the bag on the floor each rep. The shifting sand makes the twist more dynamic.'],
            ['name' => 'Weighted Sit-Up', 'equipment' => 'Sandbag', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Obliques'], 'description' => 'Lie on your back, hold the sandbag against your chest or overhead. Perform a full sit-up, curling the torso toward the knees. The sandbag adds resistance while its shifting mass challenges stability.'],
            ['name' => 'V-Up (Pass Through)', 'equipment' => 'Sandbag', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Obliques'], 'description' => 'Lie flat, hold the sandbag between hands and feet or just hands. Simultaneously raise legs and upper body to form a V, passing the bag from hands to feet at the top. Lower and repeat.'],
            ['name' => 'Plank Drag (Through)', 'equipment' => 'Sandbag', 'category_slug' => 'core', 'target_muscles' => ['Transverse Abdominis', 'Rectus Abdominis', 'Obliques', 'Shoulders'], 'description' => 'Place the sandbag on the floor beside you in a plank position. Reach across with one hand and drag the bag to the other side, keeping the hips stable. Alternating sides challenges anti-rotation.'],
            ['name' => 'Bear Crawl with Drag', 'equipment' => 'Sandbag', 'category_slug' => 'endurance', 'target_muscles' => ['Quadriceps', 'Hamstrings', 'Shoulders', 'Core', 'Glutes'], 'description' => 'Assume a bear crawl position with the sandbag on the floor behind you, attached by a harness or just touching. Crawl forward dragging the bag. Full-body conditioning and stability.'],
            ['name' => 'Sandbag Carry (Bear Hug)', 'equipment' => 'Sandbag', 'category_slug' => 'endurance', 'target_muscles' => ['Core', 'Biceps', 'Forearms', 'Quadriceps', 'Glutes', 'Traps'], 'description' => 'Hug the sandbag tightly to the chest and walk for distance or time. Maintain an upright posture; the shifting weight demands constant core and grip adjustment.'],
            ['name' => 'Zercher Carry', 'equipment' => 'Sandbag', 'category_slug' => 'endurance', 'target_muscles' => ['Core', 'Biceps', 'Upper Back', 'Quadriceps', 'Glutes'], 'description' => 'Cradle the sandbag in the elbows and walk. The forward load challenges the upper back to keep the torso from collapsing forward.'],
            ['name' => 'Overhead Carry', 'equipment' => 'Sandbag', 'category_slug' => 'stability', 'target_muscles' => ['Shoulders', 'Triceps', 'Core', 'Traps'], 'description' => 'Press the sandbag overhead with arms locked and walk. Maintain a stable overhead position; the shifting load forces continuous shoulder and core corrections.'],
            ['name' => 'Suitcase Carry', 'equipment' => 'Sandbag', 'category_slug' => 'stability', 'target_muscles' => ['Obliques', 'Core', 'Forearms', 'Gluteus Medius'], 'description' => 'Carry the sandbag in one hand at your side like a suitcase. Walk without leaning to the side. The bag\'s instability heightens the anti-lateral flexion demand.'],
            ['name' => 'Back Carry (On Shoulders)', 'equipment' => 'Sandbag', 'category_slug' => 'endurance', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core', 'Traps'], 'description' => 'Clean the sandbag to one shoulder or drape it across the back of the neck. Walk for distance. The load compresses the spine slightly less than a front carry.'],
            ['name' => 'Sandbag Slam (Ground)', 'equipment' => 'Sandbag', 'category_slug' => 'power', 'target_muscles' => ['Latissimus Dorsi', 'Triceps', 'Abdominals', 'Quadriceps', 'Glutes'], 'description' => 'Lift the sandbag overhead, then forcefully slam it to the ground in front. Squat to pick it up and repeat. Due to low bounce, this is more of a controlled slam into a mat or grass.'],
            ['name' => 'Rotational Slam', 'equipment' => 'Sandbag', 'category_slug' => 'power', 'target_muscles' => ['Obliques', 'Latissimus Dorsi', 'Glutes', 'Quadriceps', 'Core'], 'description' => 'Hold the sandbag at one hip, rotate the torso, and slam the bag to the ground beside the opposite foot. The shifting weight adds a rotational challenge.'],
            ['name' => 'Windshield Wiper (Lateral Bag Drag)', 'equipment' => 'Sandbag', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis'], 'description' => 'Lie on your back with the sandbag on the floor to one side. Keeping the legs straight up or slightly bent, use the core to swing the legs to the other side, dragging the bag with your feet. Return.'],
            ['name' => 'Turkish Get-Up (Partial)', 'equipment' => 'Sandbag', 'category_slug' => 'mobility', 'target_muscles' => ['Shoulders', 'Core', 'Glutes', 'Hamstrings', 'Rotator Cuff'], 'description' => 'Lie on your back holding the sandbag overhead with one hand. Slowly stand up by moving through a series of positions while keeping the bag stable. Lower back down. The shifting sand greatly increases difficulty.'],
            ['name' => 'Bent Press', 'equipment' => 'Sandbag', 'category_slug' => 'mobility', 'target_muscles' => ['Shoulders', 'Triceps', 'Core', 'Obliques', 'Hamstrings'], 'description' => 'Clean the sandbag to one shoulder. With a side bend, press the bag overhead while the torso leans to the side, then straighten up. The shifting load tests shoulder and spine stability.'],
            ['name' => 'Half-Kneeling Shoulder Press', 'equipment' => 'Sandbag', 'category_slug' => 'strength', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Core'], 'description' => 'Kneel with one knee up, one down. Hold the sandbag at the shoulder of the same side as the down knee. Press it overhead. The unstable position engages the core to prevent lateral bending.'],
            ['name' => 'Lateral Raise (Small Sandbag)', 'equipment' => 'Sandbag', 'category_slug' => 'isolation', 'target_muscles' => ['Medial Deltoids', 'Supraspinatus'], 'description' => 'If the sandbag is small enough, hold it in one hand. Raise the arm out to the side to shoulder height, then lower. The awkward grip forces the deltoid to work harder.'],
            ['name' => 'Front Raise (Small Sandbag)', 'equipment' => 'Sandbag', 'category_slug' => 'isolation', 'target_muscles' => ['Anterior Deltoids'], 'description' => 'Hold the sandbag with both hands in front of thighs. Raise it straight forward to shoulder height, then lower. The bag\'s bulk challenges shoulder flexion.'],
            ['name' => 'Bent-Over Lateral Raise', 'equipment' => 'Sandbag', 'category_slug' => 'isolation', 'target_muscles' => ['Rear Deltoids', 'Rhomboids', 'Infraspinatus'], 'description' => 'Hinge forward, hold a light sandbag in one or both hands hanging below. Raise it out to the sides until arms are parallel to the floor, squeezing the rear delts.'],
            ['name' => 'Reverse Fly (Standing)', 'equipment' => 'Sandbag', 'category_slug' => 'isolation', 'target_muscles' => ['Rear Deltoids', 'Rhomboids'], 'description' => 'Hold the sandbag with both hands in front at chest height, arms straight. Open the arms wide to the sides, squeezing the shoulder blades. The bag\'s inertia resists the movement.'],
            ['name' => 'Calf Raise (Standing)', 'equipment' => 'Sandbag', 'category_slug' => 'isolation', 'target_muscles' => ['Gastrocnemius', 'Soleus'], 'description' => 'Hold the sandbag across the upper back or hug it. Stand with the balls of the feet on a step, raise the heels as high as possible, then lower.'],
            ['name' => 'Sandbag Burpee', 'equipment' => 'Sandbag', 'category_slug' => 'cardio', 'target_muscles' => ['Full Body', 'Quadriceps', 'Glutes', 'Shoulders', 'Core'], 'description' => 'Hold the sandbag, squat to place it on the floor, jump feet back into a plank, perform a push-up on the bag, jump feet forward, clean the bag to the chest, and jump up, pressing overhead (optional).'],
            ['name' => 'Mountain Climbers (Hands on Bag)', 'equipment' => 'Sandbag', 'category_slug' => 'cardio', 'target_muscles' => ['Quadriceps', 'Hip Flexors', 'Core', 'Shoulders'], 'description' => 'Place both hands on the sandbag in a plank position. Drive the knees alternately toward the chest as fast as possible while keeping the bag stable.'],
            ['name' => 'Squat Jump (with Sandbag)', 'equipment' => 'Sandbag', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Calves', 'Core'], 'description' => 'Hold the sandbag at the chest. Squat down and explosively jump upward, extending the legs. Land softly and go straight into the next squat. The shifting weight makes jumping harder.'],
            ['name' => 'Broad Jump (with Sandbag)', 'equipment' => 'Sandbag', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Calves', 'Core'], 'description' => 'Hold the sandbag at the chest. Squat and jump forward for distance, landing and sticking the landing. Reset and repeat.'],
            ['name' => 'Lateral Bound (Skater Jump)', 'equipment' => 'Sandbag', 'category_slug' => 'power', 'target_muscles' => ['Glutes', 'Quadriceps', 'Adductors', 'Calves', 'Core'], 'description' => 'Hold the sandbag at the chest. Jump laterally from one foot to the other, landing softly. The bag\'s momentum challenges lateral stability.'],
        ];

        foreach ($execises as $data) {
            Exercise::create([
                'name' => $data['name'],
                'equipment' => $data['equipment'],
                'category_id' => $categories[$data['category_slug']],
                'target_muscles' => $data['target_muscles'],
                'description' => $data['description'],
            ]);
        }
    }
}
