<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\ExerciseCategory;
use Illuminate\Database\Seeder;

class SlamBallSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ExerciseCategory::pluck('id', 'slug');

        $exercises = [
            ['name' => 'Overhead Slam', 'equipment' => 'Slam Ball', 'category_slug' => 'power', 'target_muscles' => ['Latissimus Dorsi', 'Triceps', 'Abdominals', 'Quadriceps', 'Glutes'], 'description' => 'Lift the ball overhead with both hands, rise onto toes, then forcefully slam it to the ground directly in front, squatting slightly to catch or pick up the ball. Repeat explosively.'],
            ['name' => 'Rotational Slam (Side Slam)', 'equipment' => 'Slam Ball', 'category_slug' => 'power', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Latissimus Dorsi', 'Glutes', 'Quadriceps'], 'description' => 'Hold the ball at one hip, rotate torso to the opposite side, then explosively twist and slam the ball to the ground next to the opposite foot. Alternate sides.'],
            ['name' => 'Rainbow Slam', 'equipment' => 'Slam Ball', 'category_slug' => 'power', 'target_muscles' => ['Obliques', 'Latissimus Dorsi', 'Shoulders', 'Core'], 'description' => 'Start with ball at one hip, arc it overhead in a rainbow motion and slam it down to the other side. Focuses on rotational power and core control.'],
            ['name' => 'Squat to Overhead Slam', 'equipment' => 'Slam Ball', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Latissimus Dorsi', 'Shoulders', 'Core'], 'description' => 'Hold ball at chest, perform a full squat, then as you rise, lift the ball overhead and slam it down forcefully. Return to squat and repeat.'],
            ['name' => 'Split Stance Slam', 'equipment' => 'Slam Ball', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core', 'Shoulders'], 'description' => 'Stand in a split stance, ball overhead, slam the ball down while maintaining the stance, then catch or pick up. Alternates legs or stays on one side.'],
            ['name' => 'Lateral Slam (Side-to-Side)', 'equipment' => 'Slam Ball', 'category_slug' => 'power', 'target_muscles' => ['Obliques', 'Adductors', 'Abductors', 'Quadriceps', 'Glutes'], 'description' => 'Hold ball overhead, step to the side and slam the ball beside the leading foot. Repeat alternating sides, moving laterally.'],
            ['name' => 'Chest Pass Slam', 'equipment' => 'Slam Ball', 'category_slug' => 'power', 'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids', 'Triceps', 'Core'], 'description' => 'Face a wall or partner, hold the ball at chest height, explosively push it forward with both hands against the ground or wall, catch after bounce, repeat.'],
            ['name' => 'Overhead Throw (Forward)', 'equipment' => 'Slam Ball', 'category_slug' => 'power', 'target_muscles' => ['Anterior Deltoids', 'Triceps', 'Latissimus Dorsi', 'Core', 'Quadriceps'], 'description' => 'Stand holding the ball overhead, step forward and throw it as far as possible against the ground or to a partner, engaging the lats and core.'],
            ['name' => 'Backward Overhead Throw', 'equipment' => 'Slam Ball', 'category_slug' => 'power', 'target_muscles' => ['Glutes', 'Hamstrings', 'Quadriceps', 'Shoulders', 'Core'], 'description' => 'Squat with ball between legs, then explosively extend hips and throw the ball backward over the head as far as possible. Tests posterior chain power.'],
            ['name' => 'Slam Ball Russian Twist', 'equipment' => 'Slam Ball', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis'], 'description' => 'Sit on floor with knees bent, lean back, hold slam ball with both hands, rotate side to side tapping the ball on the ground each rep.'],
            ['name' => 'Slam Ball V-Up', 'equipment' => 'Slam Ball', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Obliques'], 'description' => 'Lie flat, hold ball between hands and feet or just hands, simultaneously raise legs and upper body to form a V, passing ball from hands to feet at top, then lower.'],
            ['name' => 'Slam Ball Sit-Up and Slam', 'equipment' => 'Slam Ball', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Anterior Deltoids', 'Triceps'], 'description' => 'Lie back with ball overhead, perform a sit-up, and at the top explosively slam the ball to the ground in front, catch and repeat.'],
            ['name' => 'Slam Ball Woodchop (High-to-Low)', 'equipment' => 'Slam Ball', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Transverse Abdominis', 'Rectus Abdominis', 'Shoulders'], 'description' => 'Hold the ball overhead to one side, chop diagonally across the body to the opposite hip, rotating the torso. Return with control.'],
            ['name' => 'Slam Ball Woodchop (Low-to-High)', 'equipment' => 'Slam Ball', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Transverse Abdominis', 'Rectus Abdominis', 'Shoulders'], 'description' => 'Start with ball at one hip, pull upward diagonally across the body to the opposite overhead position, engaging core.'],
            ['name' => 'Slam Ball Plank with Roll', 'equipment' => 'Slam Ball', 'category_slug' => 'core', 'target_muscles' => ['Transverse Abdominis', 'Rectus Abdominis', 'Obliques', 'Shoulders'], 'description' => 'Assume a plank with hands or forearms on the ball. Roll the ball slightly forward and back by shifting the body, maintaining a rigid core.'],
            ['name' => 'Slam Ball Mountain Climbers', 'equipment' => 'Slam Ball', 'category_slug' => 'cardio', 'target_muscles' => ['Quadriceps', 'Hip Flexors', 'Core', 'Shoulders'], 'description' => 'Place both hands on the ball in a plank position, drive knees alternately toward the chest as fast as possible while keeping the ball stable.'],
            ['name' => 'Slam Ball Burpee', 'equipment' => 'Slam Ball', 'category_slug' => 'cardio', 'target_muscles' => ['Full Body', 'Quadriceps', 'Glutes', 'Shoulders', 'Core'], 'description' => 'Hold ball, slam it to the ground, jump feet back into plank, perform a push-up on the ball or floor, jump feet forward, pick up ball, and jump to start.'],
            ['name' => 'Slam Ball Squat and Press', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Shoulders', 'Triceps', 'Core'], 'description' => 'Hold ball at chest, squat down, then as you stand, press the ball overhead. Combines lower and upper body strength.'],
            ['name' => 'Slam Ball Goblet Squat', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold the ball vertically against your chest with both hands, squat until thighs are parallel, keeping torso upright, then stand.'],
            ['name' => 'Slam Ball Overhead Squat', 'equipment' => 'Slam Ball', 'category_slug' => 'mobility', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Shoulders', 'Core'], 'description' => 'Hold the ball overhead with arms straight, squat as deep as possible while keeping the ball stabilized overhead. Tests shoulder and core stability.'],
            ['name' => 'Slam Ball Front Squat (Bear Hug)', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core', 'Biceps'], 'description' => 'Hug the ball tightly against your chest with arms wrapped around it, perform a squat, maintaining the bear hug position.'],
            ['name' => 'Slam Ball Lunges (Walking or Static)', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold ball at chest, perform forward or reverse lunges, keeping torso upright. Can alternate legs or stay in place.'],
            ['name' => 'Slam Ball Lunge with Twist', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Obliques', 'Core'], 'description' => 'Hold ball at chest, step forward into a lunge, rotate the torso toward the front leg while keeping ball tight, return and alternate.'],
            ['name' => 'Slam Ball Split Squat', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold ball at chest, take a staggered stance with one foot forward, lower until back knee nearly touches the ground, then drive up.'],
            ['name' => 'Slam Ball Step-Up', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold ball at chest, step onto a box or bench with one foot, drive through the heel to stand, then lower back down.'],
            ['name' => 'Slam Ball Glute Bridge', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Core'], 'description' => 'Lie on back, knees bent, place the ball on the hips or hold it across the pelvis, drive through heels to lift hips, squeeze glutes at top.'],
            ['name' => 'Slam Ball Hip Thrust', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Core'], 'description' => 'Sit on floor, upper back against a bench, ball across the hips, thrust upward to full extension, squeezing glutes at the top.'],
            ['name' => 'Slam Ball Hamstring Curl (Floor Slide)', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Core'], 'description' => 'Lie on back, heels on the ball, lift hips, then curl the ball toward you by bending the knees, rolling it, then extend back.'],
            ['name' => 'Slam Ball Single-Leg Deadlift', 'equipment' => 'Slam Ball', 'category_slug' => 'stability', 'target_muscles' => ['Hamstrings', 'Glutes', 'Core', 'Balance'], 'description' => 'Hold ball in both hands or one hand, stand on one leg, hinge forward while extending the free leg behind, return to standing.'],
            ['name' => 'Slam Ball Push-Up', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Pectoralis Major', 'Triceps', 'Anterior Deltoids', 'Core'], 'description' => 'Place one or both hands on the ball and perform push-ups. The unstable surface forces greater stabilizer engagement.'],
            ['name' => 'Slam Ball Chest Press (Floor)', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids', 'Triceps'], 'description' => 'Lie on floor holding ball at chest, press straight up to lockout, lower with control. Can be done one arm at a time for core challenge.'],
            ['name' => 'Slam Ball Fly (Floor)', 'equipment' => 'Slam Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids'], 'description' => 'Lie on floor, ball held above chest with arms slightly bent, lower it out to the sides in a wide arc, then squeeze back together.'],
            ['name' => 'Slam Ball Pullover', 'equipment' => 'Slam Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Latissimus Dorsi', 'Pectoralis Major', 'Serratus Anterior', 'Triceps'], 'description' => 'Lie across a bench with upper back supported, hold ball with both hands overhead, pull it over the chest in an arc until above the hips.'],
            ['name' => 'Slam Ball Bent-Over Row', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Biceps', 'Rear Deltoids', 'Erector Spinae'], 'description' => 'Hinge forward with flat back, hold ball with both hands, row it to the lower abdomen, squeezing shoulder blades.'],
            ['name' => 'Slam Ball Single-Arm Row', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi (unilateral)', 'Rhomboids', 'Biceps', 'Core'], 'description' => 'Place one knee and hand on a bench, hold ball in opposite hand, row it to the side of torso, keeping back flat.'],
            ['name' => 'Slam Ball Reverse Fly', 'equipment' => 'Slam Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Rear Deltoids', 'Rhomboids', 'Infraspinatus'], 'description' => 'Hinge at hips, hold ball with both hands hanging below, raise it out to the sides until arms are parallel, squeeze rear delts.'],
            ['name' => 'Slam Ball Upright Row', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Medial Deltoids', 'Upper Traps', 'Biceps'], 'description' => 'Hold the ball by the edges with both hands, pull it up along the body to chin height, leading with elbows.'],
            ['name' => 'Slam Ball Shrug', 'equipment' => 'Slam Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Upper Trapezius', 'Levator Scapulae'], 'description' => 'Hold ball at arm\'s length in front, shrug shoulders up toward ears, squeeze, lower.'],
            ['name' => 'Slam Ball Lateral Raise', 'equipment' => 'Slam Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Medial Deltoids', 'Supraspinatus'], 'description' => 'Stand holding ball in one hand, raise out to the side until shoulder height, lower with control. Can use both hands on a smaller ball.'],
            ['name' => 'Slam Ball Front Raise', 'equipment' => 'Slam Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Anterior Deltoids'], 'description' => 'Hold ball with both hands in front of thighs, raise straight forward to shoulder height, then lower.'],
            ['name' => 'Slam Ball Biceps Curl', 'equipment' => 'Slam Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps Brachii', 'Brachialis'], 'description' => 'Hold ball with both hands underhand, curl up by flexing elbows, squeeze at top, lower.'],
            ['name' => 'Slam Ball Hammer Curl', 'equipment' => 'Slam Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps', 'Brachialis', 'Brachioradialis'], 'description' => 'Hold ball with neutral grip (palms facing each other) in one or both hands, curl up, keeping wrists straight.'],
            ['name' => 'Slam Ball Overhead Triceps Extension', 'equipment' => 'Slam Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps Brachii (Long Head)'], 'description' => 'Hold ball with both hands overhead, lower it behind the head by bending elbows, then extend arms straight up.'],
            ['name' => 'Slam Ball Triceps Kickback', 'equipment' => 'Slam Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps Brachii (Lateral Head)'], 'description' => 'Hinge forward, hold ball in one hand, upper arm parallel to body, extend arm straight back, squeeze triceps.'],
            ['name' => 'Slam Ball Calf Raise', 'equipment' => 'Slam Ball', 'category_slug' => 'isolation', 'target_muscles' => ['Gastrocnemius', 'Soleus'], 'description' => 'Hold ball at chest, stand on balls of feet on a step, raise heels as high as possible, then lower.'],
            ['name' => 'Slam Ball Farmer\'s Carry', 'equipment' => 'Slam Ball', 'category_slug' => 'endurance', 'target_muscles' => ['Forearms', 'Traps', 'Core', 'Quadriceps', 'Glutes'], 'description' => 'Hold a ball in each hand or one heavy ball in both, walk for distance, maintaining upright posture and grip.'],
            ['name' => 'Slam Ball Suitcase Carry', 'equipment' => 'Slam Ball', 'category_slug' => 'stability', 'target_muscles' => ['Obliques', 'Core', 'Forearms', 'Gluteus Medius'], 'description' => 'Carry a heavy ball in one hand like a suitcase, walk while resisting lateral lean. Switch sides.'],
            ['name' => 'Slam Ball Overhead Carry', 'equipment' => 'Slam Ball', 'category_slug' => 'stability', 'target_muscles' => ['Shoulders', 'Triceps', 'Core', 'Traps'], 'description' => 'Press the ball overhead with one or both hands, lock arms, and walk. Maintains shoulder stability and core engagement.'],
            ['name' => 'Slam Ball Lateral Lunge', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Adductors', 'Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold ball at chest, step out to the side into a lateral lunge, sit back into the hip, then push back to start. Alternates sides.'],
            ['name' => 'Slam Ball Good Morning', 'equipment' => 'Slam Ball', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Erector Spinae', 'Core'], 'description' => 'Hold ball against chest or overhead, hinge at the hips with flat back until a stretch in hamstrings, then return.'],
            ['name' => 'Slam Ball Wall Ball', 'equipment' => 'Slam Ball', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Shoulders', 'Triceps', 'Core'], 'description' => 'Stand facing a wall, squat holding ball at chest, drive up and throw ball to a target, catch in squat position and repeat.'],
        ];

        foreach ($exercises as $data) {
            Exercise::create([
                'name' => $data['name'],
                'equipment' => $data['equipment'],
                'category_id' => $categories[$data['category_slug']],
                'target_muscles' => $data['target_muscles'],
                'description' => $data['description'],
            ]);
        }
    }
}
