<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\ExerciseCategory;
use Illuminate\Database\Seeder;

class SteelMaceSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ExerciseCategory::pluck('id', 'slug');

        $execises = [
            ['name' => 'Steel Mace 360 Swing', 'equipment' => 'Steel Mace', 'category_slug' => 'mobility', 'target_muscles' => ['Shoulders', 'Latissimus Dorsi', 'Core', 'Obliques', 'Grip'], 'description' => 'Hold the mace in both hands at the end of the handle. Swing the ball from one side of the head, behind the back, and to the other side in a full circular arc. Engages the entire shoulder girdle with rotational core strength.'],
            ['name' => 'Steel Mace 10-to-2 Swing', 'equipment' => 'Steel Mace', 'category_slug' => 'mobility', 'target_muscles' => ['Shoulders', 'Latissimus Dorsi', 'Core', 'Obliques', 'Grip'], 'description' => 'Swing the mace in a pendulum motion from one shoulder down and across the back to the other shoulder, mimicking the hands of a clock moving between 10 and 2. Improves shoulder mobility and control.'],
            ['name' => 'Steel Mace Single-Arm 360', 'equipment' => 'Steel Mace', 'category_slug' => 'mobility', 'target_muscles' => ['Shoulders (unilateral)', 'Rotator Cuff', 'Core', 'Forearms'], 'description' => 'Perform the 360 swing using only one hand. Greatly increases the stabilisation demands on the rotator cuff and grip. Switch hands each set.'],
            ['name' => 'Steel Mace Barbarian Squat', 'equipment' => 'Steel Mace', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Shoulders', 'Core'], 'description' => 'Hold the mace vertically with both hands, ball overhead or resting on the shoulder. Squat down, keeping the mace stable and upright. The offset weight challenges core stability.'],
            ['name' => 'Steel Mace Overhead Squat', 'equipment' => 'Steel Mace', 'category_slug' => 'mobility', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Shoulders', 'Core'], 'description' => 'Grip the mace with hands wide on the handle, press it overhead with arms straight. Squat as deep as possible while keeping the mace overhead. Tests shoulder and core stability.'],
            ['name' => 'Steel Mace Curtsy Squat', 'equipment' => 'Steel Mace', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Gluteus Medius', 'Hamstrings', 'Core'], 'description' => 'Hold the mace in a front rack or bear hug position. Step one leg behind and across the other into a curtsy, lowering the back knee, then return. The mace\'s weight shifts with the movement.'],
            ['name' => 'Steel Mace Lunge (Forward/Reverse)', 'equipment' => 'Steel Mace', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold the mace across the chest or in a front rack. Step forward or backward into a lunge, lowering until both knees are 90°. Drive back to start. The mace\'s length challenges balance.'],
            ['name' => 'Steel Mace Lateral Lunge', 'equipment' => 'Steel Mace', 'category_slug' => 'strength', 'target_muscles' => ['Adductors', 'Quadriceps', 'Glutes', 'Core'], 'description' => 'Hold the mace across the shoulders or in a bear hug. Step to the side, sinking into the hip while keeping the other leg straight. Push off to return. The mace loads the inside thigh.'],
            ['name' => 'Steel Mace Deadlift', 'equipment' => 'Steel Mace', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Erector Spinae', 'Core', 'Grip'], 'description' => 'Stand the mace vertically on its ball head, grip the top of the handle. Squat and hinge, pulling the mace up by extending the hips and knees. The offset handle angles increase core anti-rotation demand.'],
            ['name' => 'Steel Mace Single-Leg Deadlift', 'equipment' => 'Steel Mace', 'category_slug' => 'stability', 'target_muscles' => ['Hamstrings', 'Glutes', 'Core', 'Balance'], 'description' => 'Hold the mace in one or both hands. Stand on one leg, hinge forward while extending the free leg behind, keeping the mace close to the body. The extended mace handle challenges counterbalance.'],
            ['name' => 'Steel Mace Clean to Front Rack', 'equipment' => 'Steel Mace', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Shoulders', 'Core', 'Biceps'], 'description' => 'Hold the mace vertically with the ball on the ground. Explosively pull it upward, catching the handle with both hands and landing the ball in front of the shoulder. Builds power and coordination.'],
            ['name' => 'Steel Mace Push Press', 'equipment' => 'Steel Mace', 'category_slug' => 'power', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Quadriceps', 'Core'], 'description' => 'Hold the mace vertically in a front rack position (ball at shoulder). Dip at the knees, then drive up and press the mace overhead. The mace\'s top-heaviness forces shoulder stability.'],
            ['name' => 'Steel Mace Strict Press', 'equipment' => 'Steel Mace', 'category_slug' => 'strength', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Core'], 'description' => 'Hold the mace vertically at the shoulder. Press it overhead without leg drive, locking the arm. The long lever and top weight challenge the shoulder through the full range.'],
            ['name' => 'Steel Mace Alternating Hand Press', 'equipment' => 'Steel Mace', 'category_slug' => 'strength', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Core'], 'description' => 'Hold the mace vertically in one hand at the shoulder. Press overhead, lower, and switch hands. Unilateral shoulder strength with extreme stabiliser demand.'],
            ['name' => 'Steel Mace Bent-Over Row', 'equipment' => 'Steel Mace', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Biceps', 'Rear Deltoids', 'Erector Spinae'], 'description' => 'Hinge forward with a flat back, hold the mace handle with both hands, ball hanging between the legs. Row the mace upward by pulling the handle toward the chest. The offset weight increases core work.'],
            ['name' => 'Steel Mace Single-Arm Row', 'equipment' => 'Steel Mace', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi (unilateral)', 'Rhomboids', 'Biceps', 'Core'], 'description' => 'Support yourself on a bench with one hand, hold the mace handle in the other, and row it upward. The long handle creates a longer lever arm, challenging the lats.'],
            ['name' => 'Steel Mace Upright Row', 'equipment' => 'Steel Mace', 'category_slug' => 'strength', 'target_muscles' => ['Medial Deltoids', 'Upper Traps', 'Biceps', 'Forearms'], 'description' => 'Hold the mace handle with both hands in front of thighs. Pull it up along the body to chin height, leading with the elbows. The uneven weight distribution challenges wrist and shoulder stabilisers.'],
            ['name' => 'Steel Mace Paddle Row', 'equipment' => 'Steel Mace', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Rear Deltoids', 'Biceps'], 'description' => 'Hold the mace with both hands at the end of the handle like a canoe paddle. Hinge and row the mace ball behind you as if paddling. Engaging the lats in a different plane.'],
            ['name' => 'Steel Mace Shovel (Gravedigger)', 'equipment' => 'Steel Mace', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Obliques', 'Shoulders', 'Core'], 'description' => 'Grip the mace like a shovel, ball at one end. Perform a shovelling motion: hinge, scoop the ball back and then across the body, driving upward. Rotational power and hip drive.'],
            ['name' => 'Steel Mace Woodchop (High-to-Low)', 'equipment' => 'Steel Mace', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Transverse Abdominis', 'Rectus Abdominis', 'Shoulders'], 'description' => 'Hold the mace with both hands overhead to one side. Chop diagonally across the body, lowering the mace to the opposite hip. Rotate the torso and pivot the back foot. Return with control.'],
            ['name' => 'Steel Mace Woodchop (Low-to-High)', 'equipment' => 'Steel Mace', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Transverse Abdominis', 'Rectus Abdominis', 'Shoulders'], 'description' => 'Start with the mace at one hip. Pull it diagonally upward across the body to the opposite overhead position, rotating the torso. Engages the obliques dynamically.'],
            ['name' => 'Steel Mace Halo', 'equipment' => 'Steel Mace', 'category_slug' => 'mobility', 'target_muscles' => ['Shoulders', 'Rotator Cuff', 'Triceps', 'Core'], 'description' => 'Hold the mace vertically with both hands above the head. Circle the mace around the head at eye level, keeping the core tight. Improves shoulder mobility and control.'],
            ['name' => 'Steel Mace Triceps Extension (Overhead)', 'equipment' => 'Steel Mace', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps Brachii (Long Head)'], 'description' => 'Hold the mace vertically overhead with both hands, ball upward. Lower the ball behind the head by bending the elbows, then extend the arms straight. The top-heavy design increases the stretch.'],
            ['name' => 'Steel Mace Biceps Curl (Lever Curl)', 'equipment' => 'Steel Mace', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps Brachii', 'Brachialis', 'Forearms'], 'description' => 'Hold the mace handle with both hands, palms up. Curl the mace by flexing the elbows. The length of the mace creates a lever arm, making the weight feel heavier at the top of the curl.'],
            ['name' => 'Steel Mace Hammer Curl', 'equipment' => 'Steel Mace', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps', 'Brachialis', 'Brachioradialis'], 'description' => 'Hold the mace in one hand with a neutral grip (thumb pointing toward the ball). Curl it upward, keeping the wrist straight. The top-heavy weight intensifies brachioradialis recruitment.'],
            ['name' => 'Steel Mace Reverse Curl', 'equipment' => 'Steel Mace', 'category_slug' => 'isolation', 'target_muscles' => ['Brachioradialis', 'Wrist Extensors', 'Biceps'], 'description' => 'Grip the mace with palms down. Curl it upward, keeping the elbows stationary. The mace\'s weight distribution severely challenges the wrist extensors.'],
            ['name' => 'Steel Mace Shrug', 'equipment' => 'Steel Mace', 'category_slug' => 'isolation', 'target_muscles' => ['Upper Trapezius', 'Levator Scapulae'], 'description' => 'Hold the mace with both hands, arms straight down. Shrug the shoulders upward, squeezing at the top. The mace\'s length allows for a neutral, natural grip.'],
            ['name' => 'Steel Mace Front Raise', 'equipment' => 'Steel Mace', 'category_slug' => 'isolation', 'target_muscles' => ['Anterior Deltoids'], 'description' => 'Hold the mace handle with both hands in front of thighs, arms straight. Raise the mace straight out in front to shoulder height. The lever arm intensifies anterior delt activation.'],
            ['name' => 'Steel Mace Lateral Raise (Single Arm)', 'equipment' => 'Steel Mace', 'category_slug' => 'isolation', 'target_muscles' => ['Medial Deltoids', 'Supraspinatus'], 'description' => 'Hold the mace in one hand with the ball end behind you. Raise the arm out to the side to shoulder height. The top-heavy weight challenges lateral deltoid stability.'],
            ['name' => 'Steel Mace Russian Twist', 'equipment' => 'Steel Mace', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis'], 'description' => 'Sit on the floor, knees bent, lean back. Hold the mace with both hands or one, and rotate the torso side to side, tapping the mace on the ground each rep. The lever length increases the challenge.'],
            ['name' => 'Steel Mace Weighted Sit-Up', 'equipment' => 'Steel Mace', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors'], 'description' => 'Lie back, holding the mace against the chest or overhead. Perform a sit-up, keeping the mace stable. The extended length can add a counterbalance effect.'],
            ['name' => 'Steel Mace Plank Pull-Through', 'equipment' => 'Steel Mace', 'category_slug' => 'core', 'target_muscles' => ['Transverse Abdominis', 'Obliques', 'Rectus Abdominis', 'Shoulders'], 'description' => 'Place the mace on the floor perpendicular to your body in a plank position. Drag the mace from one side under your body to the other side with the opposite hand. Keeps the core rigid.'],
            ['name' => 'Steel Mace Slingshot (Rotational Core Swing)', 'equipment' => 'Steel Mace', 'category_slug' => 'power', 'target_muscles' => ['Obliques', 'Shoulders', 'Latissimus Dorsi', 'Core'], 'description' => 'Hold the mace horizontally at waist height, rotate the torso and whip the mace from one side to the other explosively. Simulates throwing, building rotational speed and power.'],
            ['name' => 'Steel Mace Ballistic Row (Jerk Row)', 'equipment' => 'Steel Mace', 'category_slug' => 'power', 'target_muscles' => ['Latissimus Dorsi', 'Glutes', 'Hamstrings', 'Shoulders', 'Core'], 'description' => 'Hinge forward and explosively row the mace ball toward the shoulder while extending the hips and knees. A full-body explosive pulling move.'],
            ['name' => 'Steel Mace Walking Lunge (with Rotation)', 'equipment' => 'Steel Mace', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Obliques', 'Core'], 'description' => 'Hold the mace across the chest. Step forward into a lunge, rotate the torso toward the front leg while keeping the mace horizontal or vertical. Return and alternate.'],
            ['name' => 'Steel Mace Burpee', 'equipment' => 'Steel Mace', 'category_slug' => 'cardio', 'target_muscles' => ['Full Body', 'Quadriceps', 'Glutes', 'Shoulders', 'Core'], 'description' => 'Place the mace on the floor, jump feet back into a plank, perform a push-up or just hold, jump feet forward, stand and clean the mace to the shoulder. Optionally press overhead.'],
            ['name' => 'Steel Mace Mountain Climbers (on Handle)', 'equipment' => 'Steel Mace', 'category_slug' => 'cardio', 'target_muscles' => ['Quadriceps', 'Hip Flexors', 'Core', 'Shoulders'], 'description' => 'Place both hands on the mace handle (ball on the ground) in a plank. Drive the knees alternately toward the chest. The instability of the round handle challenges core.'],
            ['name' => 'Steel Mace Calf Raise', 'equipment' => 'Steel Mace', 'category_slug' => 'isolation', 'target_muscles' => ['Gastrocnemius', 'Soleus'], 'description' => 'Hold the mace across the back of the shoulders. Stand with the balls of the feet on a step, raise the heels as high as possible, then lower.'],
            ['name' => 'Steel Mace Good Morning', 'equipment' => 'Steel Mace', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Erector Spinae', 'Core'], 'description' => 'Place the mace across the upper back, holding the handle with both hands. Hinge forward at the hips until a hamstring stretch, then return. The mace\'s length makes it easier to hold than a barbell.'],
            ['name' => 'Steel Mace Hip Thrust', 'equipment' => 'Steel Mace', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Core'], 'description' => 'Sit on the floor, upper back against a bench, mace across the hips. Drive the heels down to extend the hips upward, squeezing the glutes at the top. The padded shaft can be more comfortable on the hips.'],
        ];

        foreach ($execises as $data) {
            Exercise::create([
                'name' => $data['name'],
                'equipment' => $data['equipment'],
                'category_id' => $categories[$data['category_slug']],
                'target_muscles' => $data['target_muscles'],
                'description' => $data['description'],
            ]);
        }
    }
}
