<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\ExerciseCategory;
use Illuminate\Database\Seeder;

class SteelClubSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ExerciseCategory::pluck('id', 'slug');

        $execises = [
            ['name' => 'Steel Club Pendulum Swing (Two-Hand)', 'equipment' => 'Steel Club', 'category_slug' => 'mobility', 'target_muscles' => ['Shoulders', 'Forearms', 'Core'], 'description' => 'Hold the club with both hands, let it hang behind the head, swing it forward in a pendulum arc, and return. Improves shoulder mobility and grip.'],
            ['name' => 'Steel Club Two-Hand Swing', 'equipment' => 'Steel Club', 'category_slug' => 'mobility', 'target_muscles' => ['Shoulders', 'Latissimus Dorsi', 'Core', 'Forearms'], 'description' => 'With both hands on the handle, swing the club from behind the head, down past the legs, and back up in a smooth arc. Promotes shoulder health and core control.'],
            ['name' => 'Steel Club One-Hand Outside Swing', 'equipment' => 'Steel Club', 'category_slug' => 'mobility', 'target_muscles' => ['Shoulders', 'Rotator Cuff', 'Forearms', 'Obliques'], 'description' => 'Hold the club in one hand by the side, swing it behind the shoulder and back in a circular arc. The off-center weight challenges the rotator cuff and grip.'],
            ['name' => 'Steel Club One-Hand Inside Swing', 'equipment' => 'Steel Club', 'category_slug' => 'mobility', 'target_muscles' => ['Shoulders', 'Rotator Cuff', 'Forearms', 'Core'], 'description' => 'Swing the club across the front of the body in a circular arc, from the opposite hip to behind the shoulder. Rotates the shoulder internally and externally.'],
            ['name' => 'Steel Club Shield Cast', 'equipment' => 'Steel Club', 'category_slug' => 'strength', 'target_muscles' => ['Anterior Deltoids', 'Triceps', 'Core', 'Forearms'], 'description' => 'From a front rack (club resting on the forearm and shoulder), extend the arm forward and upward into a full lockout, like casting a shield. Builds shoulder and triceps stability.'],
            ['name' => 'Steel Club Barbarian Squat', 'equipment' => 'Steel Club', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Shoulders', 'Core'], 'description' => 'Hold one club in each hand in the front rack position. Squat down keeping the torso upright, the clubs stable on the shoulders. Challenges core and shoulder endurance.'],
            ['name' => 'Steel Club Overhead Squat', 'equipment' => 'Steel Club', 'category_slug' => 'mobility', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Shoulders', 'Core'], 'description' => 'Press a single club overhead with one or both hands, lock the arm. Squat as deep as possible while keeping the club stable. Tests shoulder mobility and stability.'],
            ['name' => 'Steel Club Front Rack Lunge', 'equipment' => 'Steel Club', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold clubs in the front rack position. Step forward or backward into a lunge, lowering the back knee, then drive up. The front load challenges core balance.'],
            ['name' => 'Steel Club Lateral Lunge', 'equipment' => 'Steel Club', 'category_slug' => 'strength', 'target_muscles' => ['Adductors', 'Quadriceps', 'Glutes', 'Core'], 'description' => 'Hold a club in one or both hands, step to the side, sink into the hip of the bent leg while keeping the other straight. Push off to return. Targets the inner thighs.'],
            ['name' => 'Steel Club Clean (to Front Rack)', 'equipment' => 'Steel Club', 'category_slug' => 'power', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Biceps', 'Shoulders', 'Core'], 'description' => 'Swing the club from between the legs upward, catching it in the front rack position (handle across the palm, club along the forearm). A dynamic full-body pull.'],
            ['name' => 'Steel Club Push Press', 'equipment' => 'Steel Club', 'category_slug' => 'power', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Quadriceps', 'Core'], 'description' => 'From the front rack, dip at the knees, then drive explosively upward and press the club overhead. Leg drive assists the press; club weight tests shoulder stability.'],
            ['name' => 'Steel Club Strict Press (Mill Press)', 'equipment' => 'Steel Club', 'category_slug' => 'strength', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Core'], 'description' => 'Hold one club in the front rack. Press it directly overhead without leg drive, locking the arm. The offset weight loads the shoulder through a full range.'],
            ['name' => 'Steel Club Alternating Press (See-Saw Press)', 'equipment' => 'Steel Club', 'category_slug' => 'strength', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Core'], 'description' => 'Hold a club in each hand in the front rack. Press one overhead while the other stays at the shoulder, alternating in a seesaw motion. Builds unilateral stability and coordination.'],
            ['name' => 'Steel Club Bent-Over Row', 'equipment' => 'Steel Club', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Biceps', 'Rear Deltoids', 'Erector Spinae'], 'description' => 'Hinge forward with a flat back, hold a club in one or both hands hanging below. Row the club(s) to the sides of the torso, squeezing the shoulder blades.'],
            ['name' => 'Steel Club Single-Arm Row (Kickstand)', 'equipment' => 'Steel Club', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi (unilateral)', 'Rhomboids', 'Biceps', 'Core'], 'description' => 'Support yourself on a bench, hold a club in the opposite hand, and row it to the hip. The club\'s length increases the lever arm, intensifying lat activation.'],
            ['name' => 'Steel Club Pullover', 'equipment' => 'Steel Club', 'category_slug' => 'isolation', 'target_muscles' => ['Latissimus Dorsi', 'Pectoralis Major', 'Serratus Anterior', 'Triceps Long Head'], 'description' => 'Lie across a bench with upper back supported, hold a single club with both hands overhead. Pull it over the chest in an arc until it\'s above the hips. Stretches the lats.'],
            ['name' => 'Steel Club Reverse Fly', 'equipment' => 'Steel Club', 'category_slug' => 'isolation', 'target_muscles' => ['Rear Deltoids', 'Rhomboids', 'Infraspinatus'], 'description' => 'Hinge forward, hold a light club in each hand hanging below. Raise the arms out to the sides until parallel to the floor, squeezing the rear delts.'],
            ['name' => 'Steel Club Upright Row', 'equipment' => 'Steel Club', 'category_slug' => 'strength', 'target_muscles' => ['Medial Deltoids', 'Upper Traps', 'Biceps', 'Forearms'], 'description' => 'Hold one club with both hands or a club in each hand. Pull the club(s) up along the body to chin height, leading with the elbows.'],
            ['name' => 'Steel Club Biceps Curl (Lever Curl)', 'equipment' => 'Steel Club', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps Brachii', 'Brachialis', 'Forearms'], 'description' => 'Hold the club handle, palm up, and curl it upward. The club\'s top-heavy design creates a lever arm, making the weight feel heavier through the mid-range.'],
            ['name' => 'Steel Club Hammer Curl (Neutral Grip)', 'equipment' => 'Steel Club', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps', 'Brachialis', 'Brachioradialis'], 'description' => 'Hold the club with a neutral grip (thumb toward the club head). Curl it upward, keeping the wrist straight. Emphasizes the brachialis and forearm.'],
            ['name' => 'Steel Club Reverse Curl', 'equipment' => 'Steel Club', 'category_slug' => 'isolation', 'target_muscles' => ['Brachioradialis', 'Wrist Extensors', 'Biceps'], 'description' => 'Grip the club with palm down, curl it upward while keeping elbows pinned. The leverage heavily taxes the wrist extensors and brachioradialis.'],
            ['name' => 'Steel Club Triceps Extension (Overhead)', 'equipment' => 'Steel Club', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps Brachii (Long Head)'], 'description' => 'Hold the club with both hands overhead, lower it behind the head by bending the elbows, then extend the arms. The club\'s shape allows a comfortable hand position.'],
            ['name' => 'Steel Club Shrug', 'equipment' => 'Steel Club', 'category_slug' => 'isolation', 'target_muscles' => ['Upper Trapezius', 'Levator Scapulae'], 'description' => 'Hold a club in each hand or one club with both, arms straight down. Shrug the shoulders up to the ears, squeeze, and lower.'],
            ['name' => 'Steel Club Lateral Raise (Single Arm)', 'equipment' => 'Steel Club', 'category_slug' => 'isolation', 'target_muscles' => ['Medial Deltoids', 'Supraspinatus'], 'description' => 'Hold the club in one hand, arm at the side. Raise it out to the side to shoulder height. The uneven weight distribution challenges the medial deltoid.'],
            ['name' => 'Steel Club Front Raise', 'equipment' => 'Steel Club', 'category_slug' => 'isolation', 'target_muscles' => ['Anterior Deltoids'], 'description' => 'Hold a club in one or both hands in front of thighs. Raise it straight forward to shoulder height. The lever arm intensifies anterior delt recruitment.'],
            ['name' => 'Steel Club Woodchop (High-to-Low)', 'equipment' => 'Steel Club', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Transverse Abdominis', 'Rectus Abdominis', 'Shoulders'], 'description' => 'Hold a single club with both hands overhead to one side. Chop diagonally across the body to the opposite hip, rotating the torso. Return with control.'],
            ['name' => 'Steel Club Woodchop (Low-to-High)', 'equipment' => 'Steel Club', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Transverse Abdominis', 'Rectus Abdominis', 'Shoulders'], 'description' => 'Start with the club at one hip, pull it diagonally upward across the body to the opposite overhead position, engaging the obliques.'],
            ['name' => 'Steel Club Russian Twist', 'equipment' => 'Steel Club', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis'], 'description' => 'Sit with knees bent, lean back, hold a club with both hands. Rotate the torso side to side, tapping the club on the floor.'],
            ['name' => 'Steel Club Weighted Sit-Up', 'equipment' => 'Steel Club', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors'], 'description' => 'Lie back, hold the club against the chest or overhead. Perform a sit-up, keeping the club stable.'],
            ['name' => 'Steel Club Plank Pull-Through', 'equipment' => 'Steel Club', 'category_slug' => 'core', 'target_muscles' => ['Transverse Abdominis', 'Obliques', 'Rectus Abdominis', 'Shoulders'], 'description' => 'In a plank position, place a club on the floor perpendicular to the body. Drag it from one side to the other with the opposite hand, keeping the hips stable.'],
            ['name' => 'Steel Club Good Morning', 'equipment' => 'Steel Club', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Erector Spinae', 'Core'], 'description' => 'Rest a club across the upper back, holding it in place. Hinge forward at the hips until a hamstring stretch, then return. The compact club size is easy to balance.'],
            ['name' => 'Steel Club Hip Thrust', 'equipment' => 'Steel Club', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Core'], 'description' => 'Sit on the floor, upper back against a bench, place a club across the hips. Thrust upward, squeezing the glutes at the top.'],
            ['name' => 'Steel Club Glute Bridge', 'equipment' => 'Steel Club', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings'], 'description' => 'Lie on the back, knees bent, club across the hips. Drive through the heels to lift the hips until straight.'],
            ['name' => 'Steel Club Single-Leg Deadlift', 'equipment' => 'Steel Club', 'category_slug' => 'stability', 'target_muscles' => ['Hamstrings', 'Glutes', 'Core', 'Balance'], 'description' => 'Hold a club in one or both hands. Stand on one leg, hinge forward extending the free leg behind, return. The club\'s offset weight challenges counterbalance.'],
            ['name' => 'Steel Club Calf Raise', 'equipment' => 'Steel Club', 'category_slug' => 'isolation', 'target_muscles' => ['Gastrocnemius', 'Soleus'], 'description' => 'Hold a club in one hand or across the shoulders, stand on the balls of the feet on a step, raise the heels high, lower.'],
            ['name' => 'Steel Club Farmer\'s Walk', 'equipment' => 'Steel Club', 'category_slug' => 'endurance', 'target_muscles' => ['Forearms', 'Traps', 'Core', 'Quadriceps', 'Glutes'], 'description' => 'Carry a heavy club in each hand by the handle, arms straight down, walk for distance. The grip and handle angle challenge the forearms.'],
            ['name' => 'Steel Club Suitcase Carry', 'equipment' => 'Steel Club', 'category_slug' => 'stability', 'target_muscles' => ['Obliques', 'Core', 'Forearms', 'Gluteus Medius'], 'description' => 'Carry a single heavy club in one hand at the side like a suitcase, walk without leaning.'],
            ['name' => 'Steel Club Overhead Carry', 'equipment' => 'Steel Club', 'category_slug' => 'stability', 'target_muscles' => ['Shoulders', 'Triceps', 'Core', 'Traps'], 'description' => 'Press a club overhead with one arm locked, walk for distance. The top-heavy club forces continuous shoulder stabilization.'],
        ];

        foreach ($execises as $data) {
            Exercise::create([
                'name' => $data['name'],
                'equipment' => $data['equipment'],
                'category_id' => $categories[$data['category_slug']],
                'target_muscles' => $data['target_muscles'],
                'description' => $data['description'],
            ]);
        }
    }
}
