<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\ExerciseCategory;
use Illuminate\Database\Seeder;

class WeightPlatesSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ExerciseCategory::pluck('id', 'slug');

        $execises = [
            ['name' => 'Plate Goblet Squat', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold a single plate vertically against your chest with both hands, elbows tucked. Squat down until thighs are parallel, keeping torso upright, then drive back up.'],
            ['name' => 'Plate Front Squat (Bear Hug)', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core', 'Biceps'], 'description' => 'Hug a large plate horizontally against your chest with arms wrapped around it. Perform a squat while maintaining a tight bear hug, emphasizing core stability.'],
            ['name' => 'Plate Overhead Squat', 'equipment' => 'Weight Plates', 'category_slug' => 'mobility', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Shoulders', 'Core'], 'description' => 'Press a single plate overhead with arms locked. Squat down while keeping the plate directly above the head, demanding shoulder mobility and core stability.'],
            ['name' => 'Plate Split Squat', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold a plate at your chest or with arms hanging. Stand in a staggered stance, lower until the back knee nearly touches the ground, then push back up.'],
            ['name' => 'Plate Bulgarian Split Squat', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Elevate rear foot on a bench, hold a plate against the chest, and squat down with the front leg, keeping the torso upright.'],
            ['name' => 'Plate Reverse Lunge', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold a plate at your chest, step backward into a lunge until both knees are at 90°, then push through the front foot to return.'],
            ['name' => 'Plate Forward Lunge', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Holding a plate, step forward into a deep lunge, lowering the rear knee toward the floor, then drive back to start.'],
            ['name' => 'Plate Walking Lunge', 'equipment' => 'Weight Plates', 'category_slug' => 'endurance', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Carry a plate at your chest and walk forward, alternating lunges. Challenges balance, coordination, and leg endurance.'],
            ['name' => 'Plate Step-Up', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], 'description' => 'Hold a plate at your chest, step onto a box or bench with one foot, drive through the heel to stand, then lower back down.'],
            ['name' => 'Plate Calf Raise (Standing)', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Gastrocnemius', 'Soleus'], 'description' => 'Hold a plate in each hand or one plate at the chest. Stand with the balls of the feet on a raised surface, raise heels as high as possible, then lower.'],
            ['name' => 'Plate Seated Calf Raise', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Soleus', 'Gastrocnemius'], 'description' => 'Sit on a bench, place a plate on top of the knees, and raise the heels by extending the ankles.'],
            ['name' => 'Plate Deadlift (Single Plate)', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Erector Spinae', 'Grip'], 'description' => 'Stand with a plate lying flat on the floor between your feet. Grip the plate by its edge (pinch grip) or through the hole, hinge at the hips, and lift it to a standing position.'],
            ['name' => 'Plate Romanian Deadlift', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Hamstrings', 'Glutes', 'Erector Spinae'], 'description' => 'Hold one or two plates in front of your thighs with both hands. Hinge at the hips, keeping a slight knee bend, and lower the plates along the legs until a stretch is felt, then return.'],
            ['name' => 'Plate Single-Leg Deadlift', 'equipment' => 'Weight Plates', 'category_slug' => 'stability', 'target_muscles' => ['Hamstrings', 'Glutes', 'Core', 'Balance'], 'description' => 'Hold a plate in one or both hands, stand on one leg, hinge forward while extending the free leg behind you, return to standing.'],
            ['name' => 'Plate Glute Bridge', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings'], 'description' => 'Lie on your back with knees bent, place a plate across your hips, drive through the heels to lift the hips until the body forms a straight line, squeeze glutes.'],
            ['name' => 'Plate Hip Thrust', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Glutes', 'Hamstrings', 'Core'], 'description' => 'Sit on the floor with upper back against a bench, plate across the hips, thrust upward to full hip extension, squeezing the glutes at the top.'],
            ['name' => 'Plate Bench Press (Floor Press)', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids', 'Triceps'], 'description' => 'Lie on the floor, hold a plate in each hand or one large plate across the chest, press straight up to lockout, then lower with control.'],
            ['name' => 'Plate Chest Fly (Floor Fly)', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Pectoralis Major', 'Anterior Deltoids'], 'description' => 'Lie on the floor, hold plates above chest with a slight elbow bend, lower them out to the sides in a wide arc, then squeeze back together.'],
            ['name' => 'Plate Pullover', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Latissimus Dorsi', 'Pectoralis Major', 'Serratus Anterior', 'Triceps Long Head'], 'description' => 'Lie across a bench with upper back supported, hold a single plate with both hands overhead, pull it over the chest in an arc until it reaches above the hips.'],
            ['name' => 'Plate Bent-Over Row (Both Arms)', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi', 'Rhomboids', 'Biceps', 'Rear Deltoids', 'Erector Spinae'], 'description' => 'Hinge forward with a flat back, hold a plate in each hand or one large plate, row them to the lower chest, squeezing shoulder blades.'],
            ['name' => 'Plate Single-Arm Row', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Latissimus Dorsi (unilateral)', 'Rhomboids', 'Biceps', 'Rear Deltoids', 'Core'], 'description' => 'Place one knee and hand on a bench, hold a plate in the opposite hand, row it to the side of the torso, keeping the back flat.'],
            ['name' => 'Plate Reverse Fly', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Rear Deltoids', 'Rhomboids', 'Infraspinatus'], 'description' => 'Hinge at the hips with plates hanging below the shoulders, raise them out to the sides until arms are parallel to the floor, squeezing the rear delts.'],
            ['name' => 'Plate Upright Row', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Medial Deltoids', 'Upper Traps', 'Biceps'], 'description' => 'Hold a plate by the edges or through the hole with both hands, pull it up along the body to chin height, leading with the elbows.'],
            ['name' => 'Plate Shrug', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Upper Trapezius', 'Levator Scapulae'], 'description' => 'Hold heavy plates at your sides with straight arms, shrug the shoulders up toward the ears, squeeze, and lower.'],
            ['name' => 'Plate Farmer\'s Walk', 'equipment' => 'Weight Plates', 'category_slug' => 'endurance', 'target_muscles' => ['Forearms', 'Traps', 'Core', 'Quadriceps', 'Glutes'], 'description' => 'Hold a heavy plate in each hand (pinch grip or through the hole) and walk for distance. Focuses on grip strength and full-body stability.'],
            ['name' => 'Plate Pinch Carry', 'equipment' => 'Weight Plates', 'category_slug' => 'endurance', 'target_muscles' => ['Forearms (Grip)', 'Fingers', 'Traps'], 'description' => 'Pinch two plates together smoothly with one hand and walk. Intensively trains pinch grip strength.'],
            ['name' => 'Plate Suitcase Carry', 'equipment' => 'Weight Plates', 'category_slug' => 'stability', 'target_muscles' => ['Obliques', 'Core', 'Forearms', 'Gluteus Medius'], 'description' => 'Carry a single heavy plate in one hand at your side while walking, keeping the torso upright to resist lateral lean.'],
            ['name' => 'Plate Overhead Carry', 'equipment' => 'Weight Plates', 'category_slug' => 'stability', 'target_muscles' => ['Shoulders', 'Triceps', 'Core', 'Traps'], 'description' => 'Press a plate overhead with one or both hands and walk, maintaining locked arms and a stable core.'],
            ['name' => 'Plate Around-the-World', 'equipment' => 'Weight Plates', 'category_slug' => 'mobility', 'target_muscles' => ['Shoulders', 'Triceps', 'Core'], 'description' => 'Hold a plate overhead, circle it around the head in a full rotation, keeping arms straight. Improves shoulder mobility and stability.'],
            ['name' => 'Plate Overhead Press (Strict)', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Core'], 'description' => 'Stand or sit, hold a plate at shoulder height with both hands, press it overhead to full arm extension without using leg drive.'],
            ['name' => 'Plate Push Press', 'equipment' => 'Weight Plates', 'category_slug' => 'power', 'target_muscles' => ['Anterior Deltoids', 'Medial Deltoids', 'Triceps', 'Quadriceps', 'Core'], 'description' => 'Dip slightly at the knees, then explosively drive upward and press the plate overhead. Leg drive assists the press.'],
            ['name' => 'Plate Lateral Raise', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Medial Deltoids', 'Supraspinatus'], 'description' => 'Stand with plates at your sides, raise them out to the sides to shoulder height, keeping a slight bend in the elbows, then lower.'],
            ['name' => 'Plate Front Raise', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Anterior Deltoids', 'Pectoralis Minor'], 'description' => 'Hold a plate by the edges with both hands in front of thighs, raise it straight forward to shoulder height, then lower slowly.'],
            ['name' => 'Plate Biceps Curl', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps Brachii', 'Brachialis'], 'description' => 'Grip the plate by the hole or edges with an underhand grip, curl it up by flexing the elbows, squeeze at the top, then lower.'],
            ['name' => 'Plate Hammer Curl (Neutral Grip)', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps', 'Brachialis', 'Brachioradialis'], 'description' => 'Hold the plate vertically with a neutral grip (palms facing each other), curl it up, keeping the wrists rigid.'],
            ['name' => 'Plate Reverse Curl', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Brachioradialis', 'Wrist Extensors', 'Biceps'], 'description' => 'Grip the plate with an overhand (pronated) grip, curl it upward while keeping elbows stationary.'],
            ['name' => 'Plate Concentration Curl', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Biceps Brachii', 'Brachialis'], 'description' => 'Sit with the back of one upper arm braced against the inner thigh, curl the plate up with that arm, isolating the bicep.'],
            ['name' => 'Plate Overhead Triceps Extension', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps Brachii (Long Head)'], 'description' => 'Hold a single plate with both hands overhead, lower it behind the head by bending the elbows, then extend the arms back up.'],
            ['name' => 'Plate French Press (Lying Triceps Extension)', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps Brachii'], 'description' => 'Lie on a bench, hold a plate with both hands above the chest, lower it toward the forehead, then press back to arm lockout.'],
            ['name' => 'Plate Kickback', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Triceps Brachii (Lateral Head)'], 'description' => 'Hinge forward, hold a plate in one hand with the upper arm parallel to the body, extend the arm straight back, squeezing the triceps.'],
            ['name' => 'Plate Russian Twist', 'equipment' => 'Weight Plates', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Rectus Abdominis', 'Transverse Abdominis'], 'description' => 'Sit on the floor with knees bent, lean back, hold a plate with both hands, and rotate the torso side to side, tapping the plate on the ground each rep.'],
            ['name' => 'Plate Weighted Sit-Up', 'equipment' => 'Weight Plates', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis', 'Hip Flexors', 'Obliques'], 'description' => 'Lie on your back, hold a plate against your chest or extended overhead, and perform a full sit-up, curling the torso toward the knees.'],
            ['name' => 'Plate Abdominal Crunch', 'equipment' => 'Weight Plates', 'category_slug' => 'core', 'target_muscles' => ['Rectus Abdominis'], 'description' => 'Lie on the floor with knees bent, hold a plate against the chest, and curl the shoulders off the floor by contracting the abs.'],
            ['name' => 'Plate Leg Raise (with Plate Between Feet)', 'equipment' => 'Weight Plates', 'category_slug' => 'core', 'target_muscles' => ['Lower Rectus Abdominis', 'Hip Flexors'], 'description' => 'Lie on a bench or floor, hold a light plate between your feet, and raise your legs until vertical, then lower with control.'],
            ['name' => 'Plate Side Bend', 'equipment' => 'Weight Plates', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Quadratus Lumborum'], 'description' => 'Stand holding a plate in one hand, bend laterally at the waist toward the plate, then return upright.'],
            ['name' => 'Plate Woodchop', 'equipment' => 'Weight Plates', 'category_slug' => 'core', 'target_muscles' => ['Obliques', 'Transverse Abdominis', 'Rectus Abdominis'], 'description' => 'Hold a plate with both hands, chop diagonally from high to low across the body while rotating the torso, returning with control.'],
            ['name' => 'Plate Halo', 'equipment' => 'Weight Plates', 'category_slug' => 'mobility', 'target_muscles' => ['Shoulders', 'Rotator Cuff', 'Triceps', 'Core'], 'description' => 'Hold the plate by the edges, circle it around the head at eye level, keeping the core tight. Opens up the shoulder girdle and strengthens stabilizers.'],
            ['name' => 'Plate Wrist Curl (Palms Up)', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Forearm Flexors'], 'description' => 'Rest forearms on thighs or a bench, hold a plate with an underhand grip, curl the wrists upward.'],
            ['name' => 'Plate Reverse Wrist Curl (Palms Down)', 'equipment' => 'Weight Plates', 'category_slug' => 'isolation', 'target_muscles' => ['Forearm Extensors'], 'description' => 'Rest forearms on thighs or bench, hold a plate with an overhand grip, extend the wrists upward.'],
            ['name' => 'Plate Pinch Press (Chest or Shoulder)', 'equipment' => 'Weight Plates', 'category_slug' => 'strength', 'target_muscles' => ['Pectoralis Major', 'Deltoids', 'Triceps', 'Grip'], 'description' => 'Pinch two plates together smoothly between your palms, press them away from the chest or overhead. Constant inward pressure engages the chest and grip.'],
            ['name' => 'Plate Swings', 'equipment' => 'Weight Plates', 'category_slug' => 'power', 'target_muscles' => ['Glutes', 'Hamstrings', 'Quadriceps', 'Core', 'Shoulders'], 'description' => 'Hold a plate by the hole with both hands, hinge at the hips, and swing it from between the legs up to chest height explosively, mimicking a kettlebell swing.'],
        ];

        foreach ($execises as $data) {
            Exercise::create([
                'name' => $data['name'],
                'equipment' => $data['equipment'],
                'category_id' => $categories[$data['category_slug']],
                'target_muscles' => $data['target_muscles'],
                'description' => $data['description'],
            ]);
        }
    }
}
